403, 404, 500 error placeholders pages added
DFE-Digital/register-trainee-teachers-prototype-old pull request #104
Opened 2020-11-04 16:00 UTC by jesseyuen

Placeholder error pages using Publish content (for now) added.

## 403

![Screenshot_2020-11-04 Register for teacher training - GOV UK(1)](https://user-images.githubusercontent.com/1108991/98134251-77ef8880-1eb6-11eb-8c0d-5783e316da4d.png)

## 404 

![Screenshot_2020-11-04 Register for teacher training - GOV UK(2)](https://user-images.githubusercontent.com/1108991/98134257-79b94c00-1eb6-11eb-8887-729f9a5fc58b.png)

## 500

![Screenshot_2020-11-04 Register for teacher training - GOV UK](https://user-images.githubusercontent.com/1108991/98134329-8d64b280-1eb6-11eb-97cd-0d8934394ba6.png)

2020-11-04 17:36 UTC, EmmaFrith commented
Have committed a few changes to this branch, let me know what you think @jesseyuen @edwardhorsford 

![Screenshot 2020-11-04 at 17 34 33](https://user-images.githubusercontent.com/56349171/98147112-01f21e00-1ec4-11eb-8416-cc9ede550018.png)

![Screenshot 2020-11-04 at 17 34 59](https://user-images.githubusercontent.com/56349171/98147168-1209fd80-1ec4-11eb-86aa-2f6eb611c916.png)

![Screenshot 2020-11-04 at 17 35 23](https://user-images.githubusercontent.com/56349171/98147210-1fbf8300-1ec4-11eb-9a7e-aa35dd209d42.png)

2020-11-04 17:46 UTC, EmmaFrith commented
further tweaks in another commit:

![Screenshot 2020-11-04 at 17 44 39](https://user-images.githubusercontent.com/56349171/98149667-6b266100-1ec5-11eb-9dc0-b02a3164641f.png)
![Screenshot 2020-11-04 at 17 45 15](https://user-images.githubusercontent.com/56349171/98149728-809b8b00-1ec5-11eb-90a6-ffc7e6398ebc.png)
![Screenshot 2020-11-04 at 17 45 48](https://user-images.githubusercontent.com/56349171/98149784-9446f180-1ec5-11eb-9636-c20df75f7ca1.png)

2020-11-06 13:28 UTC, edwardhorsford requested changes

2020-11-06 13:28 UTC, edwardhorsford commented on app/views/403.html
> +      If you think you should have access, email the Register trainee teachers team at <a class="govuk-link" href="mailto:registerateacher@digital.education.gov.uk?subject=Page%20not%20found">registe
The subject in the mailto needs fixing.

2020-11-06 13:28 UTC, edwardhorsford commented on app/views/500.html
> +      If you continue to get this message, email the Register trainee teachers team at <a class="govuk-link" href="mailto:registerateacher@digital.education.gov.uk?subject=Page%20not%20found">registe
The subject in the mailto needs fixing.

2020-11-09 09:10 UTC, jesseyuen commented on app/views/500.html
> +      If you continue to get this message, email the Register trainee teachers team at <a class="govuk-link" href="mailto:registerateacher@digital.education.gov.uk?subject=Page%20not%20found">registe
🤦‍♀️

2020-11-09 09:11 UTC, jesseyuen commented on app/views/403.html
> +      If you think you should have access, email the Register trainee teachers team at <a class="govuk-link" href="mailto:registerateacher@digital.education.gov.uk?subject=Page%20not%20found">registe
🤦‍♀️

2020-11-09 10:24 UTC, EmmaFrith requested changes
have left a comment and added a commit with some suggested content changes

2020-11-09 10:44 UTC, EmmaFrith approved these changes

2020-11-10 10:04 UTC, edwardhorsford approved these changes

2020-11-10 10:11 UTC, merged