Delete draft confirmation added
DFE-Digital/register-trainee-teachers-prototype-old pull request #160
Opened 2020-12-07 16:10 UTC by jesseyuen

![Screenshot_2020-12-07 Delete this draft record - Register trainee teachers - GOV UK(1)](https://user-images.githubusercontent.com/1108991/101374787-89a5c080-38a6-11eb-850e-706ea2a4400b.png)

2020-12-07 16:24 UTC, edwardhorsford requested changes
Looking good.

The cancel link goes to the wrong place because of it using the wrong template.

2020-12-07 16:24 UTC, edwardhorsford commented on app/views/new-record/delete-draft/confirm.html
> +{% extends "_templates/_record-form.html" %}
This is the template for existing records, not draft ones. When swapping over, check there's nothing else we're missing.

2020-12-07 16:24 UTC, edwardhorsford commented on app/views/new-record/delete-draft/confirm.html
> +{% set gridColumn = 'govuk-grid-column-full' %}
We don't want to override the default grid column

2020-12-07 16:24 UTC, edwardhorsford commented on app/views/new-record/delete-draft/confirm.html
> +{% set formAction = "./../overview" | orReferrer(referrer) %}
No need for an action

2020-12-07 16:45 UTC, edwardhorsford commented on app/views/_templates/_new-record.html
> +        {% endif %}
I don't think this is needed. The above `returnLink` handles it already.

In the view itself you can do:
`{% set returnLink = { href: 'foo', text: 'Cancel and return to record'} %}`

2020-12-08 08:01 UTC, jesseyuen commented on app/views/_templates/_new-record.html
> +        {% endif %}
You can? That's a bit fancy!

2020-12-08 10:40 UTC, jesseyuen commented on app/views/_templates/_new-record.html
> +        {% endif %}
IT WORKS!

2020-12-08 10:40 UTC, edwardhorsford approved these changes

2020-12-08 10:42 UTC, merged