Collecting placement data
DFE-Digital/register-trainee-teachers-prototype-old pull request #184
Opened 2021-02-02 19:58 UTC by jesseyuen

## Known bugs to fix

When you delete all existing placements then try to add one again you encounter a `Cannot convert undefined or null to object` error. This one's for you @edwardhorsford. 

## Outstanding tasks

Review content (Will walk you through it first @EmmaFrith)

## Things to do next

- Be smarter about collecting school name/URN
- Think about providing a clearer indication of what the minimum placements requirements are eg. "Add at least two placement details", "Add at least one more placement" etc. This is pending feedback from the ITT Market Regulation Team.

## Screenshots

### Draft

![localhost_3000_new-record_placements_can-add-placement](https://user-images.githubusercontent.com/1108991/106653928-57a39880-658f-11eb-813c-09b302529766.png)

![localhost_3000_new-record_placements_8256da9c-667f-41cb-935d-860f43caa333_details](https://user-images.githubusercontent.com/1108991/106653938-5bcfb600-658f-11eb-801a-fd27dbdb5ce5.png)

![localhost_3000_new-record_placements_confirm (1)](https://user-images.githubusercontent.com/1108991/106653959-61c59700-658f-11eb-87c9-db95740978fa.png)

![localhost_3000_new-record_placements_confirm (3)](https://user-images.githubusercontent.com/1108991/106653989-71dd7680-658f-11eb-8e17-d647af2b1b36.png)

![localhost_3000_new-record_placements_confirm (2)](https://user-images.githubusercontent.com/1108991/106653966-65591e00-658f-11eb-95d3-04d0190fea89.png)

### Record

![localhost_3000_record_36d1a4e9-802d-42c4-86ff-a52249a8bb0a](https://user-images.githubusercontent.com/1108991/106654286-d993c180-658f-11eb-8800-981afc560496.png)

![localhost_3000_record_36d1a4e9-802d-42c4-86ff-a52249a8bb0a (2)](https://user-images.githubusercontent.com/1108991/106654797-7a827c80-6590-11eb-978b-880431adcbb5.png)

![localhost_3000_record_41dc1936-9dfa-45a3-82ed-d644efadc35f_placements_confirm_referrer=_record_41dc1936-9dfa-45a3-82ed-d644efadc35f](https://user-images.githubusercontent.com/1108991/106654015-79048480-658f-11eb-8839-3dff2305b153.png)

2021-02-03 10:19 UTC, dankmitchell commented
![](https://github.trello.services/images/mini-trello-icon.png) [Prototype: collect placement data](https://trello.com/c/v1C3PmWt/832-prototype-collect-placement-data)

2021-02-03 10:22 UTC, jesseyuen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Prototype: collect placement data](https://trello.com/c/v1C3PmWt/832-prototype-collect-placement-data)

2021-02-10 11:41 UTC, EmmaFrith commented on app/views/_includes/forms/placements/placement-details.html
> +      text: "What month did this placement start?",
```suggestion
      text: "When does the placement start?",
```

2021-02-10 11:41 UTC, EmmaFrith commented on app/views/_includes/forms/placements/placement-details.html
> +    text: "How many weeks was the trainee placed there?",
```suggestion
    text: "How long does the placement last? Give the number of weeks.",
```

2021-02-10 11:41 UTC, EmmaFrith commented on app/views/_includes/forms/placements/placement-details.html
> +    text: "Enter the school, college name or reference number (URN)",
```suggestion
    text: "Enter the unique reference number (URN) of the placement school or college.",
```

2021-02-10 11:41 UTC, EmmaFrith commented on app/views/new-record/placements/can-add-placement.html
> +{% set pageHeading = "Can you add placement details for this trainee?"  %}
```suggestion
{% set pageHeading = "Do you have the trainee’s placement details?"  %}
```

2021-02-10 11:41 UTC, EmmaFrith commented on app/views/new-record/placements/can-add-placement.html
> +{% set pageHeading = "Can you add placement details for this trainee?"  %}
Perhaps somewhere on this page we should indicate that: 'You need to add placement information before you can record a training outcome.'

2021-02-10 11:41 UTC, EmmaFrith commented on app/views/_includes/forms/placements/can-add-placement.html
> +      text: "Yes"
```suggestion
      text: "Yes, I'll add them now"
```

2021-02-10 11:41 UTC, EmmaFrith commented on app/views/_includes/forms/placements/can-add-placement.html
> +      text: "Not yet, I will add placement details later"
```suggestion
      text: "No, I'll add them later"
```

2021-02-10 11:41 UTC, EmmaFrith commented on app/views/_includes/forms/placements/placement-details.html
> +    html: "<p class='govuk-hint'>Names and URNs can be found on the <a href='https://www.get-information-schools.service.gov.uk/'>Get information about schools service</a>.</p> "
```suggestion
    html: "<p class='govuk-hint'>You can <a href='https://www.get-information-schools.service.gov.uk/'>find URNs on the Get information about schools service</a>.</p> "
```

2021-02-10 11:41 UTC, EmmaFrith commented on app/views/record/placements/confirm.html
> +        text: "Have all placement details been added for the duration of the course?",
```suggestion
        text: "Have all placements been added?",
```

2021-02-10 11:41 UTC, EmmaFrith commented on app/views/_includes/summary-cards/placements/placement-details.html
> +    <p class="govuk-body">No placements have been added.<p>
```suggestion
    <p class="govuk-body">You have not added any placements yet.<p>
```

2021-02-10 11:56 UTC, edwardhorsford requested changes
First pass only - still need to try it out. One bug, I think the rest is just general code cleanup.

2021-02-10 11:56 UTC, edwardhorsford commented on app/assets/sass/overrides/_govuk-error-summary.scss
> + }
I kind of feel this should be a new component. Or at the least use a namespaced class that's not `govuk`.

2021-02-10 11:56 UTC, edwardhorsford commented on app/data/generators/placement.js
> +  })
We _might_ want to make this a bit smarter so that if the status is `QTS recommended` or `QTS awarded` then they do have placements, and they're marked as complete.

2021-02-10 11:56 UTC, edwardhorsford commented on app/lib/utils.js
> +  let needsPlacementDetails = (record?.placement?.status != 'Complete') && (placementCount <= minPlacementsRequired)
I'm not sure this is correct. Is the second part needed? I *think* it'll return true if you ever have 3 placements or _more_ than the `minPlacementsRequired`.

2021-02-10 11:56 UTC, edwardhorsford commented on app/lib/utils.js
> +  let needsPlacementDetails = (record?.placement?.status != 'Complete') && (placementCount <= minPlacementsRequired)
Isn't it just the status we need to check?

2021-02-10 11:56 UTC, edwardhorsford commented on app/routes/shared-edit-routes.js
> +  // })
Do we need all these comments?

2021-02-10 11:56 UTC, edwardhorsford commented on app/routes/shared-edit-routes.js
> +    // }
Do we need these comments?

2021-02-10 11:56 UTC, edwardhorsford commented on app/routes/shared-edit-routes.js
> +  // Add a placement - sends you to index one greater than current number of placements
This comment is not correct. It generates a UUID and sends you to it.

2021-02-10 11:56 UTC, edwardhorsford commented on app/routes/shared-edit-routes.js
> +  // Delete placement at index
This comment is not correct - it deletes a placement at a given UUID

2021-02-10 11:56 UTC, edwardhorsford commented on app/views/_includes/actions-banner.njk
> +      classes: "govuk-error-summary--advisory",
As above, would make a different namespace class for this.

2021-02-10 11:56 UTC, edwardhorsford commented on app/views/_includes/forms/placements/can-add-placement.html
> +{% endset %}
Can this be deleted? I don't think it's used.

2021-02-10 11:56 UTC, edwardhorsford commented on app/views/_includes/forms/placements/placement-details.html
> +{{record | log}}
This can be deleted.

2021-02-10 11:56 UTC, edwardhorsford commented on app/views/_includes/forms/placements/placement-details.html
> +    text: "Enter the school, college name or reference number (URN)",
I wonder if we should front-load with the URN.

2021-02-10 11:56 UTC, edwardhorsford commented on app/views/_includes/summary-cards/placements/no-placement-details.html
> +{{referrer | log}}
This can be deleted

2021-02-10 11:56 UTC, edwardhorsford commented on app/views/_includes/summary-cards/placements/placement-overview.html
> +      "text": "Add another placement" if placementCount > 0 else "Add a placement",
placementCount can't be over 0 here.

2021-02-10 11:56 UTC, edwardhorsford commented on app/views/_includes/summary-cards/placements/single-placement-details.html
> +    _text: "Location name or URN"
delete?

2021-02-10 11:56 UTC, edwardhorsford commented on app/views/new-record/placements/can-add-placement.html
> +{% endblock %} #}
Can this be deleted?

2021-02-10 11:56 UTC, edwardhorsford commented on app/views/record.html
> +{{ record | log }}
Delete

2021-02-10 11:56 UTC, edwardhorsford commented on app/views/record.html
> +{% set pageName = "Record" %}
What's this for?

2021-02-10 11:56 UTC, edwardhorsford commented on app/views/record/placements/confirm.html
> +{% set pageName = "Confirm" %}
What's this for?

2021-02-10 11:56 UTC, edwardhorsford commented on app/views/record.html
> +{% set placementCount = record.placement.items | length %}
Are these used? if not, can they be deleted?

2021-02-10 11:56 UTC, edwardhorsford commented on app/views/record.html
> +    {% include "_includes/summary-cards/placements/placement-overview.html" %}
This should be wrapped in a ` | requiresSection(placement)` thing.

2021-02-10 11:56 UTC, edwardhorsford commented on app/views/record/placements/confirm.html
> +  } | decorateAttributes(record, "record.placement.status")) }} #}
Can this be deleted?

2021-02-10 11:57 UTC, edwardhorsford commented on app/views/_includes/forms/placements/placement-details.html
> +      text: "What month did this placement start?",
@EmmaFrith my expectation is that they'll almost always be adding placements after they've started on it.

2021-02-10 12:00 UTC, edwardhorsford commented on app/views/_includes/forms/placements/placement-details.html
> +    text: "How many weeks was the trainee placed there?",
I _wonder_ if this could avoid tense entirely. We could also [use a suffix](https://design-system.service.gov.uk/components/text-input/#prefixes-and-suffixes) to confirm the units.

```suggestion
    text: "Approximate duration in weeks",
```

```suggestion
    text: "Approximate number of weeks",
```

2021-02-10 12:02 UTC, edwardhorsford commented on app/views/_includes/forms/placements/can-add-placement.html
> +      text: "Yes"
@EmmaFrith I think the question might imply answering yes only if you have details for both placements now. Whereas we want them to answer yes if they have details of at least one.

`Yes, I can add one now` perhaps?

Also, curly quote on `I’ll`

2021-02-10 12:03 UTC, edwardhorsford commented on app/views/_includes/forms/placements/can-add-placement.html
> +      text: "Not yet, I will add placement details later"
```suggestion
      text: "No, I’ll add them later"
```

2021-02-10 12:03 UTC, edwardhorsford commented on app/views/_includes/forms/placements/placement-details.html
> +    html: "<p class='govuk-hint'>Names and URNs can be found on the <a href='https://www.get-information-schools.service.gov.uk/'>Get information about schools service</a>.</p> "
@jesseyuen unsure - should this be a paragraph?

2021-02-10 12:04 UTC, edwardhorsford commented on app/views/_includes/summary-cards/placements/placement-details.html
> +    <p class="govuk-body">No placements have been added.<p>
Much nicer 👌

2021-02-10 14:01 UTC, jesseyuen commented on app/views/_includes/forms/placements/placement-details.html
> +    text: "Enter the school, college name or reference number (URN)",
> I wonder if we should front-load with the URN.

What do you mean here @edwardhorsford?

2021-02-10 14:05 UTC, jesseyuen commented on app/views/_includes/forms/placements/placement-details.html
> +    html: "<p class='govuk-hint'>Names and URNs can be found on the <a href='https://www.get-information-schools.service.gov.uk/'>Get information about schools service</a>.</p> "
The design system doesn't wrap hint text in paragraph tags so will follow that pattern although text wrapped in a <div> feels kind of weird.

2021-02-10 14:11 UTC, jesseyuen commented on app/views/_includes/forms/placements/placement-details.html
> +    text: "How many weeks was the trainee placed there?",
Have not seen the suffix documentation. I like that. @edwardhorsford @EmmaFrith

2021-02-10 14:16 UTC, jesseyuen commented on app/views/_includes/summary-cards/placements/placement-overview.html
> +      "text": "Add another placement" if placementCount > 0 else "Add a placement",
Good spot

2021-02-10 14:42 UTC, jesseyuen commented on app/assets/sass/overrides/_govuk-error-summary.scss
> + }
Agreed. I'll make this happen.

2021-02-10 15:56 UTC, jesseyuen commented on app/data/generators/placement.js
> +  })
Here we would also want to set any records seeded with `QTS recommended` or `QTS awarded` statuses to have 2 placements.

2021-02-11 09:14 UTC, jesseyuen commented on app/assets/sass/overrides/_govuk-error-summary.scss
> + }
Ok, have begun setting up a `notice-banner` component. Will move towards a unique macro in further PRs

2021-02-11 10:36 UTC, jesseyuen commented on app/views/record.html
> +    {% include "_includes/summary-cards/placements/placement-overview.html" %}
👍

2021-02-11 10:38 UTC, EmmaFrith commented on app/views/_includes/forms/placements/can-add-placement.html
> +      text: "Yes"
Ok - in that case we could use:

"Yes, I can add at least one of them now"

2021-02-11 10:54 UTC, EmmaFrith commented on app/views/data-requirements.html
> +    <p class="govuk-body">For all routes other than assessment only.</p>
```suggestion
    <p class="govuk-body">This is required for all training types except assessment only.</p>
```

2021-02-11 10:54 UTC, EmmaFrith commented on app/views/data-requirements.html
> +    <p class="govuk-body">For all routes other than assessment only.</p>
(I'm seeing what happens if we avoid "routes" in Register.)

2021-02-11 10:58 UTC, jesseyuen commented on app/views/_includes/forms/placements/can-add-placement.html
> +      text: "Yes"
Happy with this, thanks @EmmaFrith 👋

2021-02-11 10:58 UTC, jesseyuen commented on app/views/data-requirements.html
> +    <p class="govuk-body">For all routes other than assessment only.</p>
noted!

2021-02-16 11:59 UTC, edwardhorsford approved these changes
one minor comment, but otherwise looking good!

2021-02-16 11:59 UTC, edwardhorsford commented on app/data/generators/placement.js
> +// console.log({placementSchools})
Can this comment be deleted?

2021-02-16 15:08 UTC, jesseyuen commented on app/data/generators/placement.js
> +// console.log({placementSchools})
yes, yes it can.

2021-02-16 15:08 UTC, merged