content tweaks and housekeeping
DFE-Digital/register-trainee-teachers-prototype-old pull request #186
Opened 2021-02-09 13:57 UTC by EmmaFrith

A few minor changes to:

- make the prototype and build more consistent 
- tidy up some content (amends to be requested to build once updated in prototype)

This PR includes: 

- change 'Routes' to 'Type of training' (experiment whether we really need to continue with ITT jargon like 'routes')
- a comment about the potential need for hint text in the 'degree subject' section 
- change 'Last name' to 'Last names' to be more inclusive (for example, Spanish people often have two last names, and some people 2 both parents' surnames as their surname) 
- trying to be a bit clearer in the content around 'Date trainee started', and using 'Date trainee started' more consistently (for example, in the summary card)
- change 'About their training' to 'About their teacher training' to make a clear distinction with their previous education like 'Degree' 
- Add 'Trainee' to 'Contact details' for consistency with other headings like 'Trainee personal details', 'Trainee start date and ID'
- A couple of other small tweaks that felt intuitively the right thing after coming back to service with fresh eyes after a break - so shoot me!

2021-02-10 11:12 UTC, edwardhorsford requested changes

2021-02-10 11:12 UTC, edwardhorsford commented on app/views/_includes/filter-panel.njk
> +          text: "Type of training",
I'm on board with testing this, but rather cautious not using route - which seems to be overwhelmingly what the users use.

2021-02-10 11:12 UTC, edwardhorsford commented on app/views/_includes/forms/personal-details.html
> +    text: "Last names",
Why plural? [Design system suggests singular.](https://design-system.service.gov.uk/patterns/names/#labelling-name-fields)

2021-02-10 11:12 UTC, edwardhorsford commented on app/views/_includes/forms/trainee-id.html
> +    text: "You can assign your own ID for this trainee if it’ll help you identify them or search for them in your trainee records later."
For the short term, we've had to make this required. I think that might mean this hint needs to change a bit.

2021-02-10 11:12 UTC, edwardhorsford commented on app/views/_includes/forms/training-details.html
> +    This may be different to your overall programme start date. Give the date that the trainee evidenced that they are on the course.<br>
I feel like providers might struggle with 'evidenced'. I think saying it's when the trainee started is clearer.

```suggestion
    When the trainee started on the course. This may be different to your overall programme start date.<br>
```

2021-02-10 11:12 UTC, edwardhorsford commented on app/views/_includes/forms/training-details.html
> +    text: "You can assign your own ID for this trainee if it’ll help you identify them or search for them in your trainee records later."
Will need to match any changes above on the basis this is now required.

2021-02-10 11:15 UTC, EmmaFrith commented on app/views/_includes/forms/personal-details.html
> +    text: "Last names",
to be more inclusive - for example, Spanish people often have two last names, and some people 2 both parents' surnames as their surname

2021-02-10 11:21 UTC, edwardhorsford commented on app/views/_includes/forms/personal-details.html
> +    text: "Last names",
Ah I see you've said why above. Possibly one to [raise on the design system backlog](https://github.com/alphagov/govuk-design-system-backlog/issues/53)?

2021-02-10 14:37 UTC, EmmaFrith commented on app/views/_includes/forms/trainee-id.html
> +    text: "You can assign your own ID for this trainee if it’ll help you identify them or search for them in your trainee records later."
Why have we made it compulsory?

2021-02-10 14:40 UTC, EmmaFrith commented on app/views/_includes/forms/personal-details.html
> +    text: "Last names",
What do I do, just add a comment on this page? https://github.com/alphagov/govuk-design-system-backlog/issues/53

You up for trialling 'Last names' on Register?

2021-02-10 14:40 UTC, edwardhorsford commented on app/views/_includes/forms/trainee-id.html
> +    text: "You can assign your own ID for this trainee if it’ll help you identify them or search for them in your trainee records later."
For the time being, it's required by DQT.

2021-02-10 14:41 UTC, EmmaFrith commented on app/views/_includes/forms/training-details.html
> +    This may be different to your overall programme start date. Give the date that the trainee evidenced that they are on the course.<br>
I still don't know what we mean by 'started' - this seems really unclear to me.

2021-02-10 14:44 UTC, edwardhorsford commented on app/views/_includes/forms/training-details.html
> +    This may be different to your overall programme start date. Give the date that the trainee evidenced that they are on the course.<br>
It's the date the trainee started on the course. The course / programme start date is the 'official' start date for the course, but might only be as accurate to the nearest month. The trainee commencement date is when they actually started.

2021-02-10 14:50 UTC, jesseyuen commented on app/views/_includes/forms/training-details.html
> +    This may be different to your overall programme start date. Give the date that the trainee evidenced that they are on the course.<br>
I agree 'evidenced' is not the right term, it sounds made up! 

What about something where we reference the individual?

> This may be different to your overall programme start date. Give the date that the trainee **began their** training.

2021-02-10 15:21 UTC, EmmaFrith commented on app/views/_includes/forms/trainee-id.html
> +    text: "You can assign your own ID for this trainee if it’ll help you identify them or search for them in your trainee records later."
added a new commit @edwardhorsford

2021-02-10 15:23 UTC, EmmaFrith commented on app/views/_includes/forms/training-details.html
> +    text: "You can assign your own ID for this trainee if it’ll help you identify them or search for them in your trainee records later."
added more commits to attempt to resolve @edwardhorsford

2021-02-15 13:14 UTC, edwardhorsford reviewed
A couple more comments

2021-02-15 13:14 UTC, edwardhorsford commented on app/views/_includes/forms/trainee-id.html
> +    text: "Assign your own ID for this trainee to help you identify them and search for them in your trainee records. You'll also use it if you get in touch with DfE about this trainee."
```suggestion
    text: "Assign your own ID for this trainee to help you identify them and search for them in your trainee records. You’ll also use it if you get in touch with DfE about this trainee."
```

I'm not sure the second sentence is quite accurate - it's more that DfE may use it if contacting them. But I suspect they might use the trn if it's available.

2021-02-15 13:14 UTC, edwardhorsford commented on app/views/_includes/forms/training-details.html
> +    text: "This will help you to identify them and search for them in your trainee records. You can also use it if you get in touch with DfE about this trainee."
This hint text doesn't match the one above - is that intentional?

2021-02-18 13:23 UTC, EmmaFrith commented on app/views/_includes/forms/training-details.html
> +    text: "This will help you to identify them and search for them in your trainee records. You can also use it if you get in touch with DfE about this trainee."
I think this is because I changed the label here to 'Assign a trainee ID' so that I could avoid repeating 'Assign your own ID....' in the hint text and therefore make it shorter. So I *think* I did intend that :)

2021-02-19 10:34 UTC, edwardhorsford approved these changes

2021-02-19 11:28 UTC, merged