Add early years undergraduate route WIP
DFE-Digital/register-trainee-teachers-prototype-old pull request #209
Opened 2021-03-15 09:47 UTC by jesseyuen

2021-03-15 16:38 UTC, edwardhorsford requested changes

2021-03-15 16:38 UTC, edwardhorsford commented on app/data/generators/ug-entry-qualifications.js
> +}
I wonder if this file should be called `undergraduate-qualifications.js` or similar.

2021-03-15 16:38 UTC, edwardhorsford commented on app/data/generators/ug-entry-qualifications.js
> +}
Might avoid this file also having the same name as another file?

2021-03-15 16:38 UTC, edwardhorsford commented on app/filters/statuses.js
> +      // return 'govuk-tag--green'
remove

2021-03-15 16:38 UTC, edwardhorsford commented on app/filters/statuses.js
> +      return
Suggest explicitly returning the colour rather than relying on the position of the next item.

2021-03-15 16:38 UTC, edwardhorsford commented on app/data/generators/dates.js
> +  if (application.status.includes('Awarded')) {
I think this should be lowercase.

2021-03-15 16:38 UTC, edwardhorsford commented on app/views/_includes/forms/undergraduate-qualification.html
> +) }}
I do wonder if a set of radios, possibly grouped would work better here.

2021-03-15 16:38 UTC, edwardhorsford commented on app/views/_includes/summary-cards/undergraduate-qualification.html
> +    text: "Qualification"
Highest qualification?

2021-03-15 16:38 UTC, edwardhorsford commented on app/views/new-record/undergraduate-qualification/index.html
> +{% set pageHeading = "What is the trainees highest undergraduate qualification?" %}
```suggestion
{% set pageHeading = "What is the trainee’s highest undergraduate qualification?" %}
```

2021-03-15 16:38 UTC, edwardhorsford commented on app/views/record/undergraduate-qualification/confirm.html
> +
Many of these are from draft records - suggest copying a confirm page from non-draft and amending as needed.

2021-03-15 16:38 UTC, edwardhorsford commented on app/views/record/undergraduate-qualification/index.html
> +{% set pageHeading = "What is the trainees highest undergraduate qualification?" %}
```suggestion
{% set pageHeading = "What is the trainee’s highest undergraduate qualification?" %}
```

2021-03-16 09:06 UTC, jesseyuen commented on app/views/_includes/forms/undergraduate-qualification.html
> +) }}
100% agree. These are placeholder values.

2021-03-16 10:11 UTC, jesseyuen commented on app/filters/statuses.js
> +      return
Ignoring this as the dark blue status tag is the default so we dont really want to specify a modifier class.

2021-03-16 10:11 UTC, jesseyuen commented on app/views/record/undergraduate-qualification/confirm.html
> +
🤦‍♂️

2021-03-16 17:35 UTC, edwardhorsford approved these changes
Woop! 🎉

2021-03-16 17:39 UTC, merged