Add school direct routes
DFE-Digital/register-trainee-teachers-prototype-old pull request #212
Opened 2021-03-17 16:57 UTC by edwardhorsford

2021-03-23 17:11 UTC, EmmaFrith commented on app/lib/utils.js
> +        return "Trainee’s training details"
This section needs a more meaningful heading but I can't think of anything meaningful because the section is essentially miscellaneous. Split this section into at least 2 sections so that we can have meaningful headings.

2021-03-23 17:13 UTC, EmmaFrith commented on app/views/_components/school-autocomplete/template.njk
> +    text: "Search for a school"
Avoid the repetitive hint text by rolling the label and hint text into one:

Search for a school by it's unique reference number (URN), name or postcode

2021-03-24 09:04 UTC, jesseyuen requested changes

2021-03-24 09:04 UTC, jesseyuen commented on app/views/_includes/summary-cards/training-details/training-details.html
> +        visuallyHiddenText: "lead school"
```suggestion
        visuallyHiddenText: "employing school"
```

2021-03-24 09:04 UTC, jesseyuen commented on app/views/_components/school-autocomplete/template.njk
> +    text: 'Search by URN, School name or postcode'
Should `School` be capitalised? 🤔

2021-03-24 09:04 UTC, jesseyuen commented on app/lib/utils.js
> +        return "Trainee’s training details"
Agreed `Trainee’s training details` reads a bit odd. One to keep talking about!

2021-03-24 09:04 UTC, jesseyuen commented on app/routes/shared-edit-routes.js
> +        console.log(`School not found - you probably need to update the seed records`)
Is this just for our benefit?

2021-03-24 09:04 UTC, jesseyuen commented on app/views/_includes/summary-cards/training-details/training-details.html
> +{% set commencementDateLabel -%}
What does the `-` mean here again?

2021-03-24 09:04 UTC, jesseyuen commented on app/views/_includes/summary-cards/training-details/training-details.html
> +  ] %}
Consider fixing indent

2021-03-24 09:04 UTC, jesseyuen commented on app/views/new-record/training-details/employing-school.html
> +{# {% set formAction = "./confirm" | addReferrer(referrer) %} #}
Consider deleting if we dont need this

2021-03-24 09:04 UTC, jesseyuen commented on app/views/new-record/training-details/lead-school.html
> +{# {% set formAction = "./training-details/confirm" %} #}
Consider deleting if we dont need this

2021-03-24 09:04 UTC, jesseyuen commented on app/views/record.html
> +      <h2 class="govuk-heading-s">Schools</h2>
School details? 🤔

2021-03-24 09:04 UTC, jesseyuen commented on scripts/generate-schools.js
> +// const rawCities = require('../rawCities.js')
Consider deleting

2021-03-24 10:28 UTC, edwardhorsford commented on app/views/_includes/summary-cards/training-details/training-details.html
> +{% set commencementDateLabel -%}
It trims any leading whitespace coming after there.

2021-03-24 11:17 UTC, jesseyuen approved these changes

2021-03-24 11:47 UTC, edwardhorsford commented on app/lib/utils.js
> +        return "Trainee’s training details"
Have agreed with @EmmaFrith we can make this a separate task - but will come as a followup pr.

2021-03-24 11:48 UTC, edwardhorsford commented on app/routes/shared-edit-routes.js
> +        console.log(`School not found - you probably need to update the seed records`)
Yes - the seed data might refer to a school that's not in our schools data.

2021-03-24 11:50 UTC, merged