updates homepage layout
DFE-Digital/register-trainee-teachers-prototype-old pull request #308
Opened 2021-07-20 15:05 UTC by ralph-hawkins

Changes page heading from the service name (‘Register trainee teachers’) to ’Your trainee teachers’. This is to
- reduce confusion with the start page that has the same heading
- make the purpose of the page a little clearer

Adds the organisation name to the heading, this sets context for the 'Your' in 'Your trainee teachers' and will for users that belong to more than one organisation. Arguably it doesn't add a lot.

Makes the heading XL for consistency with the rest of the service and gives room in heading hierarchy for sections in the page.

Updates the nav to refer to 'trainees' consistently instead of 'records'. The service currently uses 'records' and 'trainees' either inconsistently or in a way thats pretty subtle — I personally find 'record' to be too general and find it helpful to use 'trainee'.

Removes the lead-in paragraph, this doesn't need to be seen repeatedly by users.

Styles 'Add a trainee' as a link and puts it into the new 'Draft trainees' section.

Adds sections:
- Draft trainees
- Registered trainees
- Guidance

This gives a stronger distinction between 'draft' and non-draft trainee records. This is consistent with the top nav and helps with prioritise incomplete records as a group.

The three actions in draft are shown as a simple list in part because they are conditional on whether the user has any draft trainees or records imported from Apply. If the user hasn't created any draft trainees but has records from Apply we'd only show them the 'See draft trainees imported from Apply' link because the 'all draft' link would do the exact same thing. This will also make prioritisation clearer.

Removes the middle section of the page with 3 links as the relationship between them wasn't clear and the new sections give a clearer home for the 'Registered trainees' and 'Guidance' links.

Removes the feedback link as we have it at the top of the page.

Adds a link to the current years trainees.

Reorders the status cards. Given that there are now 6 it felt odd for 'Qualification recommended' and 'Qualification awarded' to be in different rows.

Made the status cards use css-grid so they adapt to different viewport widths more nicely.

Splits the guidance links. This is so the guidance title are more useful than 'guidance'. For now the two links go to different sections in the same page, but the guidance page should be split.

Things to consider
- is the hierarchy correct, should registered trainees sit above  draft?
- we need to update the welcome email
- we need to split the guidance

![localhost_3000_home(screenshot for design history — short) (2)](https://user-images.githubusercontent.com/8417288/126347652-ca04c661-1723-4dac-8a60-dabb9e7c3e6d.png)

2021-07-21 15:51 UTC, edwardhorsford requested changes

2021-07-21 15:51 UTC, edwardhorsford commented on app/views/home.html
>  {% set recordsToBeReviewedCount = 0 %}
Can this be deleted?

2021-07-21 15:51 UTC, edwardhorsford commented on app/views/home.html
> +          <li><a href="/drafts">See all draft trainees ({{ totalDraftCount }})</a></li>
```suggestion
          <li><a class="govuk-link" href="/drafts">See all draft trainees ({{ totalDraftCount }})</a></li>
```

2021-07-21 15:51 UTC, edwardhorsford commented on app/views/home.html
> +          <li><a href="/drafts?filterSource=Apply">See draft trainees imported from Apply ({{applyDraftCount}})</a></li>
```suggestion
          <li><a class="govuk-link" href="/drafts?filterSource=Apply">See draft trainees imported from Apply ({{applyDraftCount}})</a></li>
```

2021-07-21 15:51 UTC, edwardhorsford commented on app/views/home.html
> +        <li class="govuk-!-margin-bottom-0"><a href="/new-record/new">Add a trainee</a></li>
```suggestion
        <li class="govuk-!-margin-bottom-0"><a class="govuk-link" href="/new-record/new">Add a trainee</a></li>
```

2021-07-21 15:51 UTC, edwardhorsford commented on app/views/home.html
> +        <a href="/records?filterCycle=_unchecked">See all registered trainees ({{ data.filteredRecords | filterByStatus("Draft", true)  | length}})</a>
```suggestion
        <a class="govuk-link" href="/records?filterCycle=_unchecked">See all registered trainees ({{ data.filteredRecords | filterByStatus("Draft", true)  | length}})</a>
```

2021-07-21 15:51 UTC, edwardhorsford commented on app/views/home.html
> +        <a href="/records?filterCycle=_unchecked">See all registered trainees ({{ data.filteredRecords | filterByStatus("Draft", true)  | length}})</a>
I'd create a variable at the top of this section for `nonDraftTrainees` that you can use in the count and later in the various other sections.

2021-07-21 15:51 UTC, edwardhorsford commented on app/views/home.html
> +            2020 to 2021 trainees</span> ({{ data.filteredRecords | filterByYear(["2020 to 2021"]) | filterByStatus("Draft", true)  | length}})
Use filtered nonDraft trainees from above.

2021-07-21 15:51 UTC, edwardhorsford commented on app/views/home.html
> +           –  <a href="/records?filterCycle=2020+to+2021">see all<span class="govuk-visually-hidden">
```suggestion
           –  <a class="govuk-link" href="/records?filterCycle=2020+to+2021">see all<span class="govuk-visually-hidden">
```

2021-07-21 15:51 UTC, edwardhorsford commented on app/views/home.html
> +    <div class="govuk-grid-column-full">
This needs to be in a `govuk-grid-row`?

2021-07-21 15:51 UTC, edwardhorsford commented on app/views/home.html
> +    <div class="govuk-grid-column-two-thirds-from-desktop">
This needs to be in a `govuk-grid-row`?

2021-07-21 15:51 UTC, edwardhorsford commented on app/views/home.html
> +                <a href="/records?filterStatus={{searchStatus or status}}" class="status-card status-card--{{ status | lower | kebabCase }}">
```suggestion
                <a class="govuk-link" href="/records?filterStatus={{searchStatus or status}}" class="status-card status-card--{{ status | lower | kebabCase }}">
```

2021-07-21 15:51 UTC, edwardhorsford commented on app/views/home.html
> +        <li><a href="/guidance#section-check-data">Find out about Register trainee teachers</a></li>
```suggestion
        <li><a class="govuk-link" href="/guidance#section-check-data">Find out about Register trainee teachers</a></li>
```

2021-07-21 15:51 UTC, edwardhorsford commented on app/views/home.html
> +        <li><a href="/guidance#section-about-register">Check what data you need</a></li>
```suggestion
        <li><a class="govuk-link" href="/guidance#section-about-register">Check what data you need</a></li>
```

2021-07-22 08:51 UTC, ralph-hawkins commented on app/views/home.html
>  {% set recordsToBeReviewedCount = 0 %}
I use it as a way to check if the user has created any manual drafts.

If the total draft count and drafts from apply count are the same then I infer the user has not created any drafts manually and don't show the 'See all draft trainees' link.

2021-07-22 08:57 UTC, ralph-hawkins commented on app/views/home.html
> +    <div class="govuk-grid-column-full">
I don't think so. I only use additional `govuk-grid-row`s when I want to control the position of columns at different screen widths. Given that at any width this is always a single column page we don't need the extra control and the whole page can sit in a single `govuk-grid-row`. If we need more columns later we can add more `govuk-grid-row`s.

2021-07-22 11:15 UTC, ralph-hawkins commented on app/views/home.html
> +    <div class="govuk-grid-column-full">
After feedback from design system team, we're going with more rows is better.

2021-07-22 12:43 UTC, edwardhorsford commented on app/views/home.html
>  {% set recordsToBeReviewedCount = 0 %}
I meant the line `recordsToBeReviewedCount`

2021-07-22 13:34 UTC, ralph-hawkins commented on app/views/home.html
>  {% set recordsToBeReviewedCount = 0 %}
ah — yep

2021-07-22 13:52 UTC, edwardhorsford requested changes

2021-07-22 13:52 UTC, edwardhorsford commented on app/views/home.html
> +          {% set statusString = status %}
Needs insetting
```suggestion
            {% set statusString = status %}
```

2021-07-22 13:52 UTC, edwardhorsford commented on app/views/home.html
> +                {% set searchStatus = ['EYTS recommended', 'QTS recommended'] %}
I think to get the filters working this could do
```suggestion
                {% set searchStatus = "EYTS recommended&filterStatus=QTS recommended" %}
```

2021-07-22 13:52 UTC, edwardhorsford commented on app/views/home.html
> +                {% set searchStatus = ['EYTS awarded', 'QTS awarded'] %}
Needs updating to make the filters work correctly.

2021-07-22 14:57 UTC, edwardhorsford approved these changes

2021-07-26 08:25 UTC, merged