Course level question
DFE-Digital/register-trainee-teachers-prototype-old pull request #320
Opened 2021-08-03 16:46 UTC by edwardhorsford

Collaboration with @ralph-hawkins 

When adding course details, we'll now ask up front whether it's a primary or secondary course. This means we can offer a better choice of subjects and age ranges as we know what's appropriate. 

We've also seen some participants struggle to complete the form when adding trainees on primary courses. We think this is because they don't instinctively think of those courses as having subjects. By asking about the level first, we can show a clear question that gets the data we need.

Level question
![Screenshot 2021-08-03 at 17 43 46](https://user-images.githubusercontent.com/2204224/128054100-2dea9bcc-1a1d-4a60-86e0-1621df637ecc.png)

Primary course details
![Screenshot 2021-08-03 at 17 44 12](https://user-images.githubusercontent.com/2204224/128054103-178741ad-8849-4502-80b2-310bbb845948.png)

If selecting other subject:
![Screenshot 2021-08-03 at 17 44 20](https://user-images.githubusercontent.com/2204224/128054121-fa3ffafd-e74f-4d16-8b17-4fdac6bd3023.png)

Secondary course details:
![Screenshot 2021-08-03 at 17 44 59](https://user-images.githubusercontent.com/2204224/128054217-640fe3f9-2d33-40ae-92c7-43b1d61ac01f.png)

Other implementation details:

* Age ranges shown in `other` vary depending on primary or secondary. Where an age range crosses levels, it's shown in *both* sets.
* Doesn't apply to Early years as they're essentially all one level.

2021-08-12 16:11 UTC, ralph-hawkins commented on app/views/new-record/course-details/level.html
> +{% set pageHeading = "What type of course?" %}
```suggestion
{% set pageHeading = "Which stage of education?" %}  
```

I think 'type of course' is too vague. Wikipedia use 'Educational stage' — https://en.wikipedia.org/wiki/Educational_stage — Not sure I love it. @gregknight1 any thoughts?

2021-08-12 16:11 UTC, ralph-hawkins commented on app/views/_includes/summary-cards/course-details/non-publish-course.html
> +      text: "Course type"
```suggestion
      text: "Education stage"
```

2021-08-12 16:11 UTC, ralph-hawkins commented on app/views/_includes/summary-cards/course-details/publish-course.html
> +    text: "Course type"
```suggestion
    text: "Education stage"
```

2021-08-12 16:24 UTC, edwardhorsford commented on app/views/new-record/course-details/level.html
> +{% set pageHeading = "What type of course?" %}
I'll defer to @gregknight1 on this.

2021-08-12 16:41 UTC, gregknight1 commented on app/views/new-record/course-details/level.html
> +{% set pageHeading = "What type of course?" %}
I've mulled this over quite a bit @ralph-hawkins and I get why you think it's vague. We're asking about the course the person will be doing and I felt it important that we referenced that in the heading. But then it gets a bit messy, for example - Which age group is the course to teach? or Which stage of education is the course to teach? Hence why I suggested keeping it vague but allowing the radio labels to do the heavy lifting.

Happy to be persuaded that we don't need to reference the course in the heading and expanding on your suggestion, we could have:

Which education level? 
Which phase of education?

Would also need to be consistent with the heading in the filter too.

2021-08-12 17:06 UTC, ralph-hawkins commented on app/views/new-record/course-details/level.html
> +{% set pageHeading = "What type of course?" %}
You're right it's clear enough from the options, but we have quite a few vague questions. 

For example 'what course are they doing?' and 'what type of training are they doing?').

The main area of benefit i think it brings is the summary page where you can save the user having to scan the value to infer the key. Having said that, this is only a benefit if 'Education stage' is something users recognise.

Not sure about 'level' because of the similarity to 'qualification level'.

Maybe phase is good?

2021-08-12 17:13 UTC, gregknight1 commented on app/views/new-record/course-details/level.html
> +{% set pageHeading = "What type of course?" %}
Yeah - really good point about the number of vague questions we've got. Been doing things in Publish today and that has them too. Agree with the 'level' thing too - wanted to move away from that

I'm happy for it to be 'phase' ie 'Which phase of education?' then 'Education phase' in the filter and summary.

I think that's a more recognised term than 'stage'.

2021-08-13 12:36 UTC, ralph-hawkins requested changes
I think we're agreed on 'Education phase'?

2021-08-13 12:36 UTC, ralph-hawkins commented on app/routes/records-list-routes.js
> +      heading: { text: 'Course type' },
```suggestion
      heading: { text: 'Education phase' },
```

2021-08-13 12:36 UTC, ralph-hawkins commented on app/views/_includes/filter-panel/level.njk
> +      text: "Course type",
```suggestion
      text: "Education phase",
```

2021-08-13 12:36 UTC, ralph-hawkins commented on app/views/new-record/course-details/level.html
> +{% set pageHeading = "What type of course?" %}
```suggestion
{% set pageHeading = "Which phase of education will the trainee teach?" %}  
```

2021-08-13 12:45 UTC, gregknight1 commented on app/routes/records-list-routes.js
> +      heading: { text: 'Course type' },
> I think we're agreed on 'Education phase'?

Yes

2021-08-13 12:45 UTC, ralph-hawkins requested changes

2021-08-13 12:45 UTC, ralph-hawkins commented on app/views/_includes/summary-cards/course-details/publish-course.html
> +        visuallyHiddenText: "level"
```suggestion
        visuallyHiddenText: "education phase"
```

2021-08-13 13:45 UTC, ralph-hawkins approved these changes
Nice!

2021-08-16 13:19 UTC, merged