Only ask for start dates after trainee has started their course
DFE-Digital/register-trainee-teachers-prototype-old pull request #332
Opened 2021-08-31 09:15 UTC by ralph-hawkins

We currently ask for a trainee’s start date before they have started their course.

This means the start date is predicted, but it needs to be their actual start date so we can only ask for it after the start date of the course.

This PR removes start date from the trainee record creation and Apply trainee record confirmation flowa:

![localhost_3000_new-record_training-details_confirm_referrer=_new-record_overview(screenshot)](https://user-images.githubusercontent.com/8417288/131475258-d43d7f82-e42e-4009-9f6e-6c6e719ef1ba.png)

![localhost_3000_new-record_overview(screenshot)](https://user-images.githubusercontent.com/8417288/131475263-44e616a0-094a-4ecb-932f-0bc5a35520c8.png)

It adds a check when the user confirms the record is correct and asks for a start date:
![localhost_3000_new-record_trainee-start-date(screenshot) (1)](https://user-images.githubusercontent.com/8417288/131475608-13ca724f-3a7e-4690-bda6-f3d189e4aece.png)

It changes the behaviour of the completed record. If a ITT start date is in the future, it no longer shows the outstanding actions banner. Instead it shows a message showing the course start date and hides the change link if the course hasn't started yet.

![localhost_3000_record_2ffe8d30-8b62-427c-8397-bb74285c85ae(screenshot)](https://user-images.githubusercontent.com/8417288/131476130-0c5dd85d-5fdd-4af0-95f5-7be8016e7b88.png)

If the trainee record has a start date, when the user edits the start date, they get a date input to edit.
![localhost_3000_record_2ffe8d30-8b62-427c-8397-bb74285c85ae_trainee-start-date_referrer=_record_2ffe8d30-8b62-427c-8397-bb74285c85ae(screenshot)](https://user-images.githubusercontent.com/8417288/131476399-d66833ac-135f-44fc-8a27-5a63f1d12ccc.png)

2021-08-31 09:58 UTC, ralph-hawkins commented on app/views/record.html
> +{{ record | log }}
```suggestion
```

2021-08-31 09:58 UTC, ralph-hawkins commented on app/views/record.html
> +
```suggestion
```

2021-09-01 16:20 UTC, edwardhorsford requested changes

2021-09-01 16:20 UTC, edwardhorsford commented on app/routes/existing-record-routes.js
> +    console.log( {courseStartDate, traineeStarted, commencementDate} )
Delete

2021-09-01 16:20 UTC, edwardhorsford commented on app/routes/new-record-routes.js
> +    let ittStartDate = moment(data.record.courseDetails.startDate)
Delete

2021-09-01 16:20 UTC, edwardhorsford commented on app/routes/new-record-routes.js
> +    else if (ittStartDate.isBefore()){
```suggestion
    else if (utils.isInPast(record?.courseDetails?.startDate)){
```

2021-09-01 16:20 UTC, edwardhorsford commented on app/routes/new-record-routes.js
> +  router.post('/new-record/trainee-start-date', (req, res) => {
I think we should make a new post url for this as the action performed is so different than what the url implies.

2021-09-01 16:20 UTC, edwardhorsford commented on app/views/_includes/forms/training-details/trainee-start-date.html
> +    </p>
Ideally this would use the `isPageHeading` option as part of the date input and not a separate h1

2021-09-01 16:20 UTC, edwardhorsford commented on app/views/_includes/summary-cards/trainee-progress.html
> +  {% if not record.courseDetails.startDate | isInPast() %}
```suggestion
  {% if not record.courseDetails.startDate | isInPast %}
```

2021-09-01 16:20 UTC, edwardhorsford commented on app/views/_includes/summary-cards/trainee-progress.html
> +    {{ "Course has not started" if not record | courseDatesAreAmbiguous else "ITT has not started" }}
Could flip this logic round to avoid the `not`
```suggestion
    {{ "ITT has not started" if  record | courseDatesAreAmbiguous else "Course has not started" }}
```

2021-09-01 16:20 UTC, edwardhorsford commented on app/views/_includes/summary-cards/trainee-progress.html
> +  {% if not record.courseDetails.startDate | isInPast() %}
I think we might want a filter `isInFuture`. Would make this logic cleaner.

2021-09-01 16:20 UTC, edwardhorsford commented on app/views/_includes/summary-cards/trainee-progress.html
> +  } if canAmend and record.courseDetails.startDate | isInPast()
```suggestion
  } if canAmend and record.courseDetails.startDate | isInPast
```

Brackets not needed if not passing any arguments

2021-09-01 16:20 UTC, edwardhorsford commented on app/views/_includes/summary-cards/training-details/training-details.html
> +  traineeStartDateRow if record | isDraft and false,
I suspect this line could be removed and the entire row deleted? I don't think we ever want start date in the summary card?

2021-09-01 16:20 UTC, edwardhorsford commented on app/views/record.html
> +          {% if not record.courseDetails.startDate | isInPast() %}
```suggestion
          {% if not record.courseDetails.startDate | isInPast %}
```

Wonder if `isInFuture` would be a helpful filter here.

2021-09-01 16:20 UTC, edwardhorsford commented on app/views/record.html
> +            text: courseNotStartedMessage | safe,
```suggestion
            text: courseNotStartedMessage,
```

2021-09-01 16:20 UTC, edwardhorsford commented on app/views/record.html
> +          {% elif record | hasOutstandingActions %}
```suggestion
          {% elseif record | hasOutstandingActions %}
```

2021-09-01 16:20 UTC, edwardhorsford commented on app/views/record.html
> +            <a href="{{referrer}}/defer" class="govuk-link--no-visited-state">Defer</a> or <a href="{{referrer}}/withdraw" class="govuk-link--no-visited-state">withdraw</a> this trainee</p>
```suggestion
              <a href="{{referrer}}/defer" class="govuk-link--no-visited-state">Defer</a> or <a href="{{referrer}}/withdraw" class="govuk-link--no-visited-state">withdraw</a> this trainee
            </p>
```

Trying to fix indentation here. Not sure github has got it right though.

2021-09-03 13:41 UTC, edwardhorsford requested changes

2021-09-03 13:41 UTC, edwardhorsford commented on app/lib/utils.js
> +  if (!traineeStarted && ittStartDate.isBefore()) {
Think this should use the `isInPast` filter.

2021-09-06 08:47 UTC, ralph-hawkins commented on app/lib/utils.js
> +  if (!traineeStarted && ittStartDate.isBefore()) {
Done

2021-09-06 14:39 UTC, edwardhorsford approved these changes

2021-09-06 14:40 UTC, merged