Delete, defer or withdraw routes can handle missing start dates
DFE-Digital/register-trainee-teachers-prototype-old pull request #346
Opened 2021-09-22 10:22 UTC by ralph-hawkins

# Summary

Trainees can only be deferred or withdrawn if they have started their course. Now that we can have records without start dates, we need to collect start dates before a user can defer or withdraw a trainee. We also need to give users something they can do with a record if the trainee has not started but does not take their place on the course, so records can be deleted if the trainee did not start their course.

# Screenshots

If the course that has not started yet, the trainee record can be deleted.

![localhost_3000_record_e811b894-a680-49d7-a1fc-e6877e383500(screenshot) (1)](https://user-images.githubusercontent.com/8417288/134322591-e4adc735-04c3-4c03-911e-5f770649c7a6.png)

If the course has started, but the record doesn't have a trainee start date, the user is shown options to delete, defer and withdraw. When the user deletes, defers or withdraws they will be asked if the trainee started their course.

![localhost_3000_record_e811b894-a680-49d7-a1fc-e6877e383500(screenshot) (2)](https://user-images.githubusercontent.com/8417288/134323306-dbb2232b-ce58-415b-a0db-448fba4e3fca.png)

## Delete flow

If the course has not started or the trainee did not start the course, the record can be deleted.

![localhost_3000_record_e811b894-a680-49d7-a1fc-e6877e383500_delete_confirm_referrer=_record_e811b894-a680-49d7-a1fc-e6877e383500(screenshot)](https://user-images.githubusercontent.com/8417288/134326244-0fbb6a1c-25ea-469b-8ba5-2149b0d26026.png)

If the course start date is in the past, when the user tries to delete, defer or withdraw, they are asked if the trainee started their course.

![localhost_3000_record_e811b894-a680-49d7-a1fc-e6877e383500_delete_did-trainee-start_referrer=_record_e811b894-a680-49d7-a1fc-e6877e383500(screenshot)](https://user-images.githubusercontent.com/8417288/134324273-6b7058c8-ac3a-4909-8e68-862dc4c84fd6.png)

If the trainee did start the course, the user will be asked when they started their course.

![localhost_3000_record_e811b894-a680-49d7-a1fc-e6877e383500_delete_when-did-trainee-start_referrer=_record_e811b894-a680-49d7-a1fc-e6877e383500(screenshot)](https://user-images.githubusercontent.com/8417288/134324423-ad90db15-a283-4321-9bd5-3db356ec655a.png)

If the trainee has started their course, the user is told they cannot delete the trainee’s record.

![localhost_3000_record_e811b894-a680-49d7-a1fc-e6877e383500_delete_cannot-delete(screenshot)](https://user-images.githubusercontent.com/8417288/134324628-916cb240-66f9-4b55-8f4f-2d9329b223c1.png)

## Defer flow

If the trainee has not started their course, they cannot be deferred.

![localhost_3000_record_e811b894-a680-49d7-a1fc-e6877e383500_defer_cannot-defer_referrer=_record_e811b894-a680-49d7-a1fc-e6877e383500(screenshot)](https://user-images.githubusercontent.com/8417288/134326392-89d26469-963d-4c2e-80ec-c5ce8307f8e1.png)

## Withdraw flow

If the trainee has not started their course, they cannot be withdrawn. This PR also removes the 'Did not start the course' option for reason trainee is withdrawing.

![localhost_3000_record_e811b894-a680-49d7-a1fc-e6877e383500_withdraw_cannot-withdraw_referrer=_record_e811b894-a680-49d7-a1fc-e6877e383500(screenshot)](https://user-images.githubusercontent.com/8417288/134324959-56564342-336d-489b-a0d8-2f1b3479ce95.png)

2021-09-22 14:34 UTC, edwardhorsford requested changes

2021-09-22 14:34 UTC, edwardhorsford commented on app/lib/utils.js
> +  if ((dates.isInPast(courseStartDate)) && (status == "Pending TRN" || status == "TRN received")) {
Feels like this filter overlaps a lot with the filters in `statuses.js` - `canDefer` and `canWithdraw`?

2021-09-22 14:34 UTC, edwardhorsford commented on app/lib/utils.js
> +exports.needTraineeStartDateCheck = (record) => {
This filter feels oddly named - `needsTraineeStartDate`?

2021-09-22 14:34 UTC, edwardhorsford commented on app/routes/existing-record-routes.js
> +  router.post('/record/:uuid/delete/when-did-trainee-start', (req, res) => {
```suggestion
  router.post('/record/:uuid/delete/did-trainee-start-answer', (req, res) => {
```

2021-09-22 14:34 UTC, edwardhorsford commented on app/routes/existing-record-routes.js
> +    let commencementDate = record?.trainingDetails?.commencementDate
don't think this line is used

2021-09-22 14:34 UTC, edwardhorsford commented on app/routes/existing-record-routes.js
> +      res.redirect(`/record/${req.params.uuid}/delete/cannot-delete${referrer}`)
Are both these redirects meant to be the same? If so, move out of the if statement entirely.

2021-09-22 14:34 UTC, edwardhorsford commented on app/routes/existing-record-routes.js
> +  router.post('/record/:uuid/defer/when-did-trainee-start', (req, res) => {
```suggestion
  router.post('/record/:uuid/defer/did-trainee-start-answer', (req, res) => {
```

2021-09-22 14:34 UTC, edwardhorsford commented on app/routes/existing-record-routes.js
> +      res.redirect(`/record/${req.params.uuid}/defer${referrer}`)
these redirects look identical? if so move outside if statement

2021-09-22 14:34 UTC, edwardhorsford commented on app/routes/existing-record-routes.js
> +  router.post('/record/:uuid/withdraw/when-did-trainee-start', (req, res) => {
```suggestion
  router.post('/record/:uuid/withdraw/did-trainee-start-answer', (req, res) => {
```

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/_includes/forms/did-trainee-start.html
> +      text: pageHeading,
```suggestion
      text: pageHeading,
      isPageHeading: true,
```

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/_includes/record-actions.njk
> +  {% set deleteUrl    = referrer + "/delete/did-trainee-start"   | addReferrer(referrer) %}
I don't think `referrer` is the right thing to use here on the left hand side. Use `recordPath` instead perhaps? They'll equate to the same thing though.

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/_includes/record-actions.njk
> +{% if record | needTraineeStartDateCheck %}
Update this if this filter gets renamed.

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/_includes/record-actions.njk
> +  {% set deferUrl     = referrer + "/defer/"                     | addReferrer(referrer) %}
```suggestion
  {% set deferUrl     = referrer + "/defer"                     | addReferrer(referrer) %}
```

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/_includes/record-actions.njk
> +  {% set deferUrl     = referrer + "/defer/"                     | addReferrer(referrer) %}
I don't think the trailing slash is correct.

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/_includes/record-actions.njk
> +  {% set withdrawUrl  = referrer + "/withdraw/"                  | addReferrer(referrer) %}
```suggestion
  {% set withdrawUrl  = referrer + "/withdraw"                  | addReferrer(referrer) %}
```

Don't think trailing slash is correct.

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/defer/did-trainee-start.html
> +{% set formAction = "./when-did-trainee-start" | addReferrer(referrer) %}
```suggestion
{% set formAction = "./did-trainee-start-answer" | addReferrer(referrer) %}
```

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/defer/did-trainee-start.html
> +  Did the trainee start their {{ "ITT" if record | courseDatesAreAmbiguous else "course" }}?
```suggestion
  Did the trainee start their {{ "ITT" if data.record | courseDatesAreAmbiguous else "course" }}?
```

In the context of this template, `record` doesn't yet exist - so I think this will always render as `course`

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/defer/did-trainee-start.html
> +  {{ record.trainingDetails.traineeStarted | log }}
Delete

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/defer/did-trainee-start.html
> +  </h1>
Should this be within the form template below?

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/defer/when-did-trainee-start.html
> +  Did the trainee start their {{ "ITT" if record | courseDatesAreAmbiguous else "course" }} on time?
```suggestion
  Did the trainee start their {{ "ITT" if data.record | courseDatesAreAmbiguous else "course" }} on time?
```

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/defer/when-did-trainee-start.html
> +  </h1>
Should this be within the template below?


FWIW most of my form templates include the h1. But perhaps that's the wrong approach and they'd be better at this level.

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/delete/cannot-delete.html
> +{% set action = "deleted" %}
Might avoid using the name `action` in case that gets conflated with form actions.

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/delete/did-trainee-start.html
> +{% set formAction = "./when-did-trainee-start" | addReferrer(referrer) %}
```suggestion
{% set formAction = "./did-trainee-start-answer" | addReferrer(referrer) %}
```

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/delete/did-trainee-start.html
> +  Did the trainee start their {{ "ITT" if record | courseDatesAreAmbiguous else "course" }}?
```suggestion
  Did the trainee start their {{ "ITT" if data.record | courseDatesAreAmbiguous else "course" }}?
```

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/delete/cannot-delete.html
> +{% set withdrawPath  = "/record/" + data.record.id + "/withdraw/" | addReferrer(referrer) %}
You probably don't need to set these - you can probably just have relative urls directly set

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/_includes/cannot-complete-task-content.html
> +    You can <a href="{{ deferPath }}">defer</a> or <a href="{{ withdrawPath }}">withdraw</a> this trainee.
Not sure you need to pass `deferPath` or `withdrawPath` in to this include - isn't the url always the same?

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/delete/when-did-trainee-start.html
> +{% set formAction = "./cannot-delete" %}
```suggestion
{% set formAction = "./cannot-delete" %}
```

should this be `when-did-trainee-start-answer`?

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/delete/when-did-trainee-start.html
> +  Did the trainee start their {{ "ITT" if record | courseDatesAreAmbiguous else "course" }} on time?
```suggestion
  Did the trainee start their {{ "ITT" if data.record | courseDatesAreAmbiguous else "course" }} on time?
```

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/did-trainee-start.html
> +  Did the trainee start their {{ "ITT" if record | courseDatesAreAmbiguous else "course" }}?
```suggestion
  Did the trainee start their {{ "ITT" if data.record | courseDatesAreAmbiguous else "course" }}?
```

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/did-trainee-start.html
> +{% set formAction = "./when-did-trainee-start" %}
```suggestion
{% set formAction = "./did-trainee-start-answer" %}
```

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/did-trainee-start.html
> +  {{ record.trainingDetails.traineeStarted | log }}
Delete

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/when-did-trainee-start.html
> +  Did the trainee start their {{ "ITT" if record | courseDatesAreAmbiguous else "course" }} on time?
```suggestion
  Did the trainee start their {{ "ITT" if data.record | courseDatesAreAmbiguous else "course" }} on time?
```

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/withdraw/cannot-withdraw.html
> +{% set deletePath = "/record/" + record.id + "/delete/confirm" %}
don't think you need this?

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/withdraw/did-trainee-start.html
> +{% set formAction = "./when-did-trainee-start" | addReferrer(referrer) %}
```suggestion
{% set formAction = "./did-trainee-start-answer" | addReferrer(referrer) %}
```

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/withdraw/did-trainee-start.html
> +  Did the trainee start their {{ "ITT" if record | courseDatesAreAmbiguous else "course" }}?
```suggestion
  Did the trainee start their {{ "ITT" if data.record | courseDatesAreAmbiguous else "course" }}?
```

2021-09-22 14:34 UTC, edwardhorsford commented on app/views/record/withdraw/when-did-trainee-start.html
> +  Did the trainee start their {{ "ITT" if record | courseDatesAreAmbiguous else "course" }} on time?
```suggestion
  Did the trainee start their {{ "ITT" if data.record | courseDatesAreAmbiguous else "course" }} on time?
```

2021-09-23 09:30 UTC, ralph-hawkins commented on app/lib/utils.js
> +  if ((dates.isInPast(courseStartDate)) && (status == "Pending TRN" || status == "TRN received")) {
I've removed `canDefer` (there is no 'canWithdraw') as I think showDeferAndWithdraw is more accurate — we don't want to know if the trainee can defer (or withdraw) where we use it, we just need to know if we should show them the option.

2021-09-24 09:20 UTC, dankmitchell commented
![](https://github.trello.services/images/mini-trello-icon.png) [Delete, defer and withdraw without a start date](https://trello.com/c/OeMYPJoc/2685-delete-defer-and-withdraw-without-a-start-date)

2021-09-27 14:06 UTC, edwardhorsford approved these changes
Nice work man! 🎉

2021-09-27 14:14 UTC, merged