Service updates and patches
DFE-Digital/register-trainee-teachers-prototype-old pull request #352
Opened 2021-09-30 16:02 UTC by ralph-hawkins

2021-11-03 11:59 UTC, edwardhorsford requested changes

2021-11-03 11:59 UTC, edwardhorsford commented on app/assets/sass/application.scss
> +ul {
I think this should be scoped to a `app-markdown` class or something.

2021-11-03 11:59 UTC, edwardhorsford commented on app/data/service-patches-and-updates.json
> +}
Not sure this file is wanted any more.

2021-11-03 11:59 UTC, edwardhorsford commented on app/data/service-patches-and-updates.yaml
> +updates:
Could the filename be just `service-updates.yaml`? Patches feels rather technical

2021-11-03 11:59 UTC, edwardhorsford commented on app/data/session-data-defaults.js
> +  updatesAndPatches,
Would probably call this `serviceUpdates` or `serviceUpdatesAndNews` or something.

2021-11-03 11:59 UTC, edwardhorsford commented on app/filters/strings.js
> +  })
Could probably delete all these comments?

2021-11-03 11:59 UTC, edwardhorsford commented on app/views/service-updates.html
> +            <li><a class="govuk-link" href="#{{ update.title | escape }}">{{ update.title }}</a></li>
What's this `escape` filter? Don't we want the title camel-cased for the url?

2021-11-03 11:59 UTC, edwardhorsford commented on app/data/service-patches-and-updates.yaml
> +updates:
```suggestion
items:
```

2021-11-03 11:59 UTC, edwardhorsford commented on app/views/service-updates.html
> +          <section id="section-about-register">
This id should presumably be the title, camel-cased (there's already a filter to do this).

2021-11-03 11:59 UTC, edwardhorsford commented on app/views/service-updates.html
> +            <h2 class="govuk-heading-m govuk-!-margin-bottom-2" id="{{ update.title | escape }}">
I can see there's an ID on this h2 - wonder if this should be on the parent section instead?

2021-11-03 19:38 UTC, gregknight1 reviewed
Looks really good @ralph-hawkins. I take it there's no issue in having a link on the sign-in page. What's springing to mind is how the full list of news/updates is accessed when a user is signed in?

Wondering how we'd approach an update with a large amount of content or multiple updates at the same time.

Also thinking that the contents could end up being massive, as could the actual updates. Think we need some rules around the maintenance of this.

2021-11-12 16:08 UTC, edwardhorsford approved these changes

2021-11-12 16:09 UTC, edwardhorsford commented on app/views/service-updates.html
> +{% set backLink = '/start-page' %}
This should probably be js back - `/start-page` isn't the only source for this page.

2021-11-30 13:13 UTC, merged