Allow providers to defer trainees who haven't started
DFE-Digital/register-trainee-teachers-prototype-old pull request #361
Opened 2021-10-15 08:50 UTC by ralph-hawkins

Trainees can now be deferred if their course start date is in the future.

![localhost_3000_record_2a1eff12-ce41-4c3e-a42b-4aeae604fbdd(screenshot) (1)](https://user-images.githubusercontent.com/8417288/137458073-70d84b57-9a84-4bd6-8961-2866fb348be3.png)

Adds start date to deferral confirmation (regardless of when the trainee started). This feels relevant here and might help prevent some issues around trainees who had a predicted start date being withdrawn.

![localhost_3000_record_2a1eff12-ce41-4c3e-a42b-4aeae604fbdd_defer_confirm_referrer=_record_2a1eff12-ce41-4c3e-a42b-4aeae604fbdd(screenshot) (1)](https://user-images.githubusercontent.com/8417288/137459143-39ed548c-897d-4fd9-82a9-e9899930bca7.png)

![localhost_3000_record_2a1eff12-ce41-4c3e-a42b-4aeae604fbdd_defer_confirm_referrer=_record_2a1eff12-ce41-4c3e-a42b-4aeae604fbdd(screenshot) (2)](https://user-images.githubusercontent.com/8417288/137459398-31f56cc9-ad64-4c30-ad21-4d1b7ed635d2.png)

If the trainee didn't start their ITT before deferring the record shows that "The trainee deferred before starting their ITT" and the start date cannot be edited after a trainee has been withdrawn.

![localhost_3000_record_2a1eff12-ce41-4c3e-a42b-4aeae604fbdd(screenshot) (1)](https://user-images.githubusercontent.com/8417288/137461273-62d45b7f-1735-4625-b6a9-7ca768b646ef.png)

If a trainee is reinstated who didn't previously have a start date, the reinstatement date becomes their start date too.

### Bonus

Fixed the line length in the outstanding actions banner:

![localhost_3000_record_2a1eff12-ce41-4c3e-a42b-4aeae604fbdd(screenshot) (4)](https://user-images.githubusercontent.com/8417288/137462097-0f29e781-5dab-482d-a2a1-8f4a5849c149.png)

2021-10-19 09:34 UTC, edwardhorsford requested changes

2021-10-19 09:34 UTC, edwardhorsford commented on app/lib/utils.js
> +exports.ittInTheFuture = (record) => {
This filter seems to be necessary? It's just going to return the same as the existing `isInFuture` filter isn't it?

2021-10-19 09:34 UTC, edwardhorsford commented on app/lib/utils.js
> +exports.traineeDeferred = (record) => {
There's an existing filter `isDeferred` that returns this.

2021-10-19 09:34 UTC, edwardhorsford commented on app/routes/existing-record-routes.js
> +    // set trainee deferred date as start date if trainee withdrew before starting
```suggestion
    // Set trainee deferred date as start date if trainee deferred before starting
```

2021-10-19 09:34 UTC, edwardhorsford commented on app/views/_includes/summary-cards/defer-details.html
> +    } if canAmend and record | traineeStarted
Remind me why you can't edit this?

2021-10-19 09:34 UTC, edwardhorsford commented on app/views/_includes/summary-cards/trainee-progress.html
> +    The trainee deferred before starting their ITT
Is the deferral date no longer relevant in this case? (just checking)

2021-10-19 09:34 UTC, edwardhorsford commented on app/views/_includes/summary-cards/trainee-progress.html
> +  } if canAmend and record | ittInTheFuture and not record | traineeDeferred
Why can you only edit the start date if the ITT is in the future?

2021-10-19 09:40 UTC, ralph-hawkins commented on app/lib/utils.js
> +exports.ittInTheFuture = (record) => {
It felt cleaner to use a filter — would you prefer to use `record.courseDetails.startDate | isInFuture`?

2021-10-19 09:46 UTC, ralph-hawkins commented on app/views/_includes/summary-cards/defer-details.html
> +    } if canAmend and record | traineeStarted
It be pretty complex to resolve on the financial side if the trainee was set to having withdrawn before starting and then it was later changed? 

We could allow it to be edited, but it felt like given the itt had not started or the provider told us that the trainee had not started when the trainee was withdrawn it seemed like we could assume a reasonable amount of intent.

2021-10-19 09:47 UTC, ralph-hawkins commented on app/views/_includes/summary-cards/trainee-progress.html
> +    The trainee deferred before starting their ITT
If the trainee didn't start it the date isn't relevant, only if they did or did not start.

2021-10-19 10:15 UTC, ralph-hawkins commented on app/views/_includes/summary-cards/trainee-progress.html
> +  } if canAmend and record | ittInTheFuture and not record | traineeDeferred
I think this should be in the past!

2021-10-19 10:24 UTC, ralph-hawkins commented on app/views/_includes/summary-cards/trainee-progress.html
> +  } if canAmend and record | ittInTheFuture and not record | traineeDeferred
Fixed it

2021-10-19 10:31 UTC, edwardhorsford commented on app/lib/utils.js
> +exports.ittInTheFuture = (record) => {
It doesn't seem to add too much value to me?

2021-10-19 10:34 UTC, edwardhorsford commented on app/views/_includes/summary-cards/trainee-progress.html
> +    The trainee deferred before starting their ITT
ok!

2021-10-21 09:48 UTC, edwardhorsford commented on app/lib/utils.js
> +
This whole section can be reduced to:
```
return dates.isInFuture(record?.courseDetails?.startDate)
```

2021-10-21 09:49 UTC, edwardhorsford commented on app/lib/utils.js
> +  if (dates.isInPast(ittStartDate) && !traineeStartDate) {
```suggestion
return (dates.isInPast(ittStartDate) && !traineeStartDate)
```

2021-10-21 09:50 UTC, edwardhorsford commented on app/lib/utils.js
> +  if (dates.isInPast(ittStartDate) && traineeStartDate) {
```suggestion
 return (dates.isInPast(ittStartDate) && traineeStartDate)
```

2021-10-21 09:51 UTC, edwardhorsford approved these changes
A few of the filters could be simplified - left some suggestions.

2021-10-21 10:32 UTC, merged