adds funding page and data
DFE-Digital/register-trainee-teachers-prototype-old pull request #400
Opened 2021-11-29 10:15 UTC by ralph-hawkins

2021-11-29 15:49 UTC, edwardhorsford requested changes

2021-11-29 15:49 UTC, edwardhorsford commented on app/assets/sass/application.scss
> +$sizes: 50, 25, 20, 16;
Maybe comment / name this so it's clearer what it's for?

2021-11-29 15:49 UTC, edwardhorsford commented on app/filters/app-misc.js
> +filters.getFundingStreams = () => {
Not sure I follow the purpose of this filter. Could these have just been calculated / set in the funding.js file? If not, can you add a comment about what this is for?

2021-11-29 15:49 UTC, edwardhorsford commented on app/views/funding/academic-year-payments.html
> +    ] %}
Check indentation?

2021-11-29 15:49 UTC, edwardhorsford commented on app/views/funding/academic-year-payments.html
> +  {% endif %}
This could probably done in one line or two for readability - though what you have is fine.

One line:
{% set tierTotal = ((item.tierAmount * item.numberOfTrainees) | currency) or "–" %}

Separate line:
`{% set tierTotal = tierTotal or "–" %}

2021-11-29 15:49 UTC, edwardhorsford commented on app/views/funding/academic-year-payments.html
> +{% extends "layout.html" %}
I'd probably move this to the top of the template for consistency.

2021-11-29 15:49 UTC, edwardhorsford commented on app/views/funding/academic-year-payments.html
> +      <span class="govuk-caption-l">{{ data.signedInProviders | andSeparate }}</span>
```suggestion
      <span class="govuk-caption-xl">{{ data.signedInProviders | andSeparate }}</span>
```

2021-11-29 15:49 UTC, edwardhorsford commented on app/views/funding/academic-year-payments.html
> +{% set yearPaymentsTabName = "" | getFundingStreams %}
```suggestion
{% set yearPaymentsTabName = "" | getFundingStreams | joinify | sentenceCase %}
```

2021-11-29 15:49 UTC, edwardhorsford commented on app/views/funding/academic-year-payments.html
> +{% set yearPaymentsTabName = yearPaymentsTabName | joinify %}
```suggestion
```

2021-11-29 15:49 UTC, edwardhorsford commented on app/views/funding/academic-year-payments.html
> +      text: yearPaymentsTabName | sentenceCase,
```suggestion
      text: yearPaymentsTabName,
```

2021-11-29 15:49 UTC, edwardhorsford commented on app/views/funding/academic-year-payments.html
> +      {{ yearPaymentsTabName | sentenceCase }}
```suggestion
      {{ yearPaymentsTabName }}
```

2021-11-29 15:49 UTC, edwardhorsford commented on app/views/funding/academic-year-payments.html
> +      <a href="govuk-link--no-visited-state">Export {{ yearPaymentsTabName }}</a>
```suggestion
      <a href="govuk-link--no-visited-state">Export {{ yearPaymentsTabName | lower }}</a>
```

2021-11-29 15:49 UTC, edwardhorsford commented on app/views/funding/academic-year-payments.html
> +    }) }}
Indentation

2021-11-29 15:49 UTC, edwardhorsford commented on app/views/funding/academic-year-payments.html
> +      caption: "Bursary and scholarships",
Does this caption need to be dynamic?

2021-11-29 15:49 UTC, edwardhorsford commented on app/views/funding/monthly-payments.html
> +{% set months  = [
Add a comment for why this starts in August?

2021-11-29 15:49 UTC, edwardhorsford commented on app/views/funding/monthly-payments.html
> +{% endif %}
Could you comment what this is doing? I'd guess getting the right index in an array or something?

2021-11-29 15:49 UTC, edwardhorsford commented on app/views/funding/monthly-payments.html
> +      <a href="govuk-link--no-visited-state">Export monthly payments</a>
I think you mean this to be a class.

2021-11-30 11:43 UTC, ralph-hawkins commented on app/views/funding/academic-year-payments.html
> +      caption: "Bursary and scholarships",
yep – fixed

2021-11-30 11:43 UTC, ralph-hawkins commented on app/views/funding/monthly-payments.html
> +      <a href="govuk-link--no-visited-state">Export monthly payments</a>
woof — yeah, fixed

2021-11-30 18:07 UTC, edwardhorsford commented
It feels like there should be more space between these tables - possibly with a section break?
<img width="1078" alt="Screenshot 2021-11-30 at 17 33 36" src="https://user-images.githubusercontent.com/2204224/144098251-8e21c58b-eec9-43b6-a871-baf4cc219005.png">

2021-12-03 10:10 UTC, edwardhorsford approved these changes

2021-12-03 10:10 UTC, merged