Adds funding for lead schools and refactors all funding
DFE-Digital/register-trainee-teachers-prototype-old pull request #413
Opened 2021-12-10 09:51 UTC by ralph-hawkins

Lead school monthly payments:

![localhost_3000_funding_monthly-payments(screenshot) (2)](https://user-images.githubusercontent.com/8417288/145553831-30905b04-08ea-41b0-a0cb-15b68adeda70.png)

Lead school salaries and grants:

![localhost_3000_funding_annual-payments-lead-school(screenshot)](https://user-images.githubusercontent.com/8417288/145553909-b89c46a1-c18f-4cb1-8c2d-5ec2a5ecb7ce.png)

Accredited provider monthly payments:

![localhost_3000_funding_monthly-payments(screenshot) (3)](https://user-images.githubusercontent.com/8417288/145554004-8bd78ce7-e980-40d8-a536-0307287c0db8.png)

Accredited provider bursaries and scholarships:

![localhost_3000_funding_annual-payments-scitt(screenshot)](https://user-images.githubusercontent.com/8417288/145554142-0b9be3e2-528e-465d-8246-9c9603d0cff3.png)

2021-12-10 10:19 UTC, dankmitchell commented
![](https://github.trello.services/images/mini-trello-icon.png) [Funding — lead schools](https://trello.com/c/xXoKTXGH/3173-funding-lead-schools)

2021-12-10 12:45 UTC, edwardhorsford requested changes

2021-12-10 12:45 UTC, edwardhorsford commented on app/filters/app-misc.js
> +      console.log(`${pair[0]} is not present!`)
Delete

2021-12-10 12:45 UTC, edwardhorsford commented on app/filters/app-misc.js
> +    .replace(/(\d{2})\/(\d{2})/, '20$1&nbsp;to&nbsp;$2');
Could you add a comments for this? and an example?

2021-12-10 12:45 UTC, edwardhorsford commented on app/filters/objects.js
> +
Could you add a comment / description for this? maybe an example?

2021-12-10 12:45 UTC, edwardhorsford commented on app/filters/objects.js
> +// Filter results for only those containing attribute and value
I think this comment needs updating - we copied it from elsewhere

2021-12-10 12:45 UTC, edwardhorsford commented on app/filters/objects.js
> +filters.whereDoesNotInclude = (arr, key, compare) => {
Add comment

2021-12-10 12:45 UTC, edwardhorsford commented on app/filters/strings.js
> +  else if ( input < 0 ) { return `–£${numberWithCommas(input * -1 )}` }
I think we might want to either check that `input` is numeric or else convert to numeric

2021-12-10 12:45 UTC, edwardhorsford commented on app/filters/strings.js
> +}
I wonder if we could just use the built-in replace filter for this?

2021-12-10 12:45 UTC, edwardhorsford commented on app/views/funding/annual-payments-lead-school.html
> +  {% set tabName = "Salares and grants" %}
*Salares* lol

2021-12-10 12:45 UTC, edwardhorsford commented on app/views/funding/annual-payments-lead-school.html
> +  {% set activeTabYearlyScitt = false %}
I don't think you need to set these?

2021-12-10 12:45 UTC, edwardhorsford commented on app/views/funding/annual-payments-lead-school.html
> +  ] %}
Unclear what this is for - as it looks a bit weird, can you add a comment?

2021-12-10 12:45 UTC, edwardhorsford commented on app/views/funding/annual-payments-scitt.html
> +  {% set activeTabMonthly = false %}
Delete

2021-12-10 12:45 UTC, edwardhorsford commented on app/views/funding/annual-payments-scitt.html
> +  {% set activeTabYearlyLeadSchool = false %}
Delete

2021-12-10 12:45 UTC, edwardhorsford commented on app/views/funding/annual-payments-scitt.html
> +  {# to do – sort alphabetically by subject #}
Isn't this sorted by subject in line 28?

2021-12-10 12:45 UTC, edwardhorsford commented on app/views/funding/annual-payments-scitt.html
> +    {# Not showing this for now as its inferred #}
```suggestion
    {# Not showing this for now as it’s inferred #}
```

2021-12-10 12:45 UTC, edwardhorsford commented on app/views/funding/monthly-payments.html
> +  {# TODO #}
What is TODO?

2021-12-10 12:45 UTC, edwardhorsford commented on app/views/funding/monthly-payments.html
> +      { text: "Payments to " + currentMonth("word") + " " + currentYear() },
What is "word"?

2021-12-10 13:18 UTC, ralph-hawkins commented on app/filters/strings.js
> +}
yeah, have deleted

2021-12-10 13:28 UTC, ralph-hawkins commented on app/views/funding/annual-payments-lead-school.html
> +  ] %}
Realised this should be done with colSpan.

2021-12-10 13:34 UTC, ralph-hawkins commented on app/views/funding/monthly-payments.html
> +      { text: "Payments to " + currentMonth("word") + " " + currentYear() },
the name of the month — I've relabelled as "nameOfMonth"

2021-12-10 15:43 UTC, ralph-hawkins commented on app/filters/strings.js
> +  else if ( input < 0 ) { return `–£${numberWithCommas(input * -1 )}` }
done — though i think its ok without?

2021-12-13 16:19 UTC, edwardhorsford commented on app/filters/objects.js
> +// Delete all params where all items match params
This comment doesn't really make any sense - could you give an example?

2021-12-13 16:19 UTC, edwardhorsford commented on app/functions.js
>    functions.currentMonth = (type) => {
Should this have a default, making the param optional?

```suggestion
  functions.currentMonth = (type="number") => {
```

2021-12-13 16:19 UTC, edwardhorsford commented on app/functions.js
> +  // Get current month as "nameOfMonth" (eg December = 'December'), or number (eg December = 12)
```suggestion
  // Get current month as "nameOfMonth" (eg December = 'December'), or "number" (eg December = 12)
```

2021-12-14 10:18 UTC, edwardhorsford commented on app/views/funding/annual-payments-lead-school.html
> +      {% set subjectAndRoute = item.subject + '<br><span class="app-nowrap">' + item.route | lower | sentenceCase + '</span>' %}
This would probably be clearer as a set block.

2021-12-14 16:39 UTC, edwardhorsford approved these changes

2021-12-14 17:27 UTC, merged