updates the content for the update
DFE-Digital/register-trainee-teachers-prototype-old pull request #416
Opened 2021-12-10 16:20 UTC by ralph-hawkins

2021-12-17 13:47 UTC, edwardhorsford reviewed
My previous comment on this was that 'start date' was ambiguous - I think this could be phrased more clearly.

2022-01-20 14:57 UTC, gregknight1 requested changes

2022-01-20 14:57 UTC, gregknight1 commented on app/data/service-updates.yaml
> +      When registering a trainee, we were always asking for a start date. Now, we will only ask for a start date after the ITT has started.
When registering a trainee, we were always asking for a start date, even if the course had not started. Now, we will only ask for a start date once the course has started.

2022-01-20 14:57 UTC, gregknight1 commented on app/data/service-updates.yaml
>    - date: '2021-12-10'
2022-01-20

2022-01-20 15:26 UTC, ralph-hawkins commented on app/data/service-updates.yaml
> +      When registering a trainee, we were always asking for a start date. Now, we will only ask for a start date after the ITT has started.
When registering a trainee, we were always asking ~~for a start date~~ `when the trainee started`, even if their course had not started. Now, we will only ask ~~for a start date once the~~ `when the trainee started, after their`  course has started.

2022-01-20 15:33 UTC, gregknight1 commented on app/data/service-updates.yaml
> +      When registering a trainee, we were always asking for a start date. Now, we will only ask for a start date after the ITT has started.
Yes, agree with that @ralph-hawkins

2022-01-27 12:31 UTC, gregknight1 commented
Looks good @ralph-hawkins

2022-01-27 14:00 UTC, merged