Placement schools
DFE-Digital/register-trainee-teachers-prototype-old pull request #428
Opened 2021-12-23 15:49 UTC by edwardhorsford

This updates the placement flow to use the schools autocomplete and save a pointer to a school rather than just a name.

Also updates the seeds to pick from the GIS schools.

2022-01-06 18:39 UTC, bbelward commented
looking great so far, I like that the prompt links change depending on how much of the placement information you've completed + if you've confirmed you've added all placement info.

2022-01-12 13:23 UTC, ralph-hawkins requested changes
- Can we change "Placement details" to "Placements"?
- Should the summary card have a title?
- Having "Manage placements" in the top of the summary card feels less intuitive and inconsistent with how we've done the other change links

![register-pro-placement--gbnjsn herokuapp com_record_80d3a57d-8d87-4e7a-9630-d5d9ed5849bf(screenshot)](https://user-images.githubusercontent.com/8417288/149145331-f3de05b1-1dbd-41b8-9f1c-9042984a020c.png)

- empty state feels weird to me, i think we need use a similar pattern to empty second placement for an empty first placement

![register-pro-placement--gbnjsn herokuapp com_record_e0f185c8-b516-4253-8d9e-a3f9a9a44b46(screenshot)](https://user-images.githubusercontent.com/8417288/149146561-3788b4ad-c196-4aed-80df-06d052a6b768.png)

- Looks like there's a bug with storing placements on EYTS drafts?
- On the check draft page; "Second placement is missing" feels a bit strong, given that they might not have it yet. We could go with "...not provided"?

2022-01-12 13:23 UTC, ralph-hawkins commented on app/views/record/placements/confirm.html
> +          <a href="https://www.gov.uk/government/publications/initial-teacher-training-criteria/initial-teacher-training-itt-criteria-and-supporting-advice#c23-training-in-schools" class="govuk-link"
I find this link text a bit confusing — could we simplify it to something like "Read more about placements and training in schools".

2022-01-12 13:23 UTC, ralph-hawkins commented on app/views/record/placements/confirm.html
> +        </p>
Should we hide this when the user has given us enough placements?

2022-01-12 13:23 UTC, ralph-hawkins commented on app/views/record/placements/details-manual.html
> +{% set pageHeading = ordinalName + " placement school" %}
I wonder if this should be "setting" or similar, given that EY ITT isn't done at a school?

2022-01-13 11:31 UTC, edwardhorsford commented on app/views/record/placements/confirm.html
> +          <a href="https://www.gov.uk/government/publications/initial-teacher-training-criteria/initial-teacher-training-itt-criteria-and-supporting-advice#c23-training-in-schools" class="govuk-link"
This is placeholder till I can talk to @gregknight1

2022-01-13 11:33 UTC, edwardhorsford commented on app/views/record/placements/confirm.html
> +        </p>
Done

2022-01-13 11:34 UTC, edwardhorsford commented on app/views/record/placements/details-manual.html
> +{% set pageHeading = ordinalName + " placement school" %}
Will discuss with @gregknight1. In one of the DTTP pages it's "Organisation name"

2022-01-13 11:57 UTC, edwardhorsford commented
Updated so we'll refer to *settings* when talking about Early years
<img width="1037" alt="Screenshot 2022-01-13 at 11 56 57" src="https://user-images.githubusercontent.com/2204224/149326098-6e4a281e-b266-4ef3-9625-95a2f3ca9e73.png">

2022-01-14 14:48 UTC, ralph-hawkins commented
"Trainee" in "Trainee placement deleted" feels redundant on the success banner.

![Screenshot 2022-01-14 at 14 38 15](https://user-images.githubusercontent.com/8417288/149533320-625a05c5-aebf-4d97-8fcb-cd58bd5f00b8.png)

You've used "Placements" and "Placement details" — I'm ok with this, but its not consistent with the other titles/captions in the rest of the page.

![Screenshot 2022-01-14 at 14 40 04](https://user-images.githubusercontent.com/8417288/149533393-bcb2021c-8b03-426e-a86a-7bbbaf8ef352.png)

On the drafts — I think it would be useful to explain that the user will need to provide at least 2 placements, even if they only have details about 1 now.

![Screenshot 2022-01-14 at 14 41 30](https://user-images.githubusercontent.com/8417288/149533629-2224a069-1df5-49a7-bb31-4b57a8e40ebf.png)

The draft summary doesn't show "Placements not marked as complete" in the same way the other sections do.

![Screenshot 2022-01-14 at 14 44 50](https://user-images.githubusercontent.com/8417288/149534205-bbf08cd0-20a9-4b4f-a197-99467a936624.png)

2022-01-14 17:02 UTC, edwardhorsford commented
> "Trainee" in "Trainee placement deleted" feels redundant on the success banner.

Fixed

> You've used "Placements" and "Placement details" — I'm ok with this, but its not consistent with the other titles/captions in the rest of the page.

Fixed

> On the drafts — I think it would be useful to explain that the user will need to provide at least 2 placements, even if they only have details about 1 now.

Updated to use the same content as on the record - though expect we'll probably replace this content with something better.

> The draft summary doesn't show "Placements not marked as complete" in the same way the other sections do.

Good catch - made to match the other sections now.

2022-01-14 17:34 UTC, ralph-hawkins approved these changes
Great work, as always

2022-01-17 11:13 UTC, gregknight1 commented
![image](https://user-images.githubusercontent.com/54059249/149759690-ca8bb52f-774e-4f98-94da-1d6097490dc9.png)

Can we change this to 'Placements'

2022-01-17 16:25 UTC, edwardhorsford commented
@gregknight1 @ralph-hawkins ok, should all be updated.

2022-01-17 16:32 UTC, ralph-hawkins commented on app/views/_includes/forms/placements/can-add-placement.html
> +  <a href="https://www.gov.uk/government/publications/initial-teacher-training-criteria/initial-teacher-training-itt-criteria-and-supporting-advice#c23-training-in-schools" class="govuk-link">Read Df
`<a href="https://www.gov.uk/government/publications/initial-teacher-training-criteria/initial-teacher-training-itt-criteria-and-supporting-advice#c23-training-in-schools" class="govuk-link">Read DfE guidance about training placements in schools and <span class="app-nowrap">early years settings</span>.`

2022-01-17 16:33 UTC, ralph-hawkins commented on app/views/_includes/forms/placements/can-add-placement.html
> +  <a href="https://www.gov.uk/government/publications/initial-teacher-training-criteria/initial-teacher-training-itt-criteria-and-supporting-advice#c23-training-in-schools" class="govuk-link">Read Df
Read DfE guidance about training placements in schools and `<span class="app-nowrap">`early years settings`</span>`.

2022-01-17 16:35 UTC, ralph-hawkins commented on app/views/new-record/placements/confirm.html
> +            You need to add the details of at least {{ minPlacementsRequired }} {{ "school" | pluralise(data.settings.minPlacementsRequired) }} before you can recommend this trainee for {{ record | g
I think "school" should swap for "setting" for early years routes. Probably worth making a filter?

2022-01-17 17:13 UTC, merged