Historic trainees
DFE-Digital/register-trainee-teachers-prototype-old pull request #430
Opened 2022-01-10 17:27 UTC by ralph-hawkins

As part of retiring DTTP we're moving the historic trainees into Register. To help Register handle the extra trainees I have:
- prioritised showing trainees we think are most relative on the homepage
- added a filter on 'Draft trainees' and 'Registered trainees' to show the 'Current', 'Next year' and 'Historic' trainees
- removed the 'Start year' filter from 'Draft trainees'
- made the 'Start year' filter a select on 'Registered trainees'
- added the trainee’s 'Start year' to the 'trainee cards' (this is updated after the screenshots)

![localhost_3000_home(screenshot) (1)](https://user-images.githubusercontent.com/8417288/148810486-0a886e42-dfc3-4e78-b7ae-b7c3274ff19d.png)

![localhost_3000_drafts(screenshot)](https://user-images.githubusercontent.com/8417288/148810494-5bd78349-a409-4a61-ae67-751f1ded4ebd.png)

![localhost_3000_records_filterCycle=_unchecked filterActiveFutureHistoric=Current(screenshot)](https://user-images.githubusercontent.com/8417288/148810490-f9690fc9-4e84-4f06-9357-75be413030d8.png)

2022-01-13 11:27 UTC, edwardhorsford requested changes

2022-01-13 11:27 UTC, edwardhorsford commented on app/data/years.js
>    "2020 to 2021"
I wonder if this is redundant now? might need cleanup elsewhere in code too

2022-01-13 11:27 UTC, edwardhorsford commented on app/filters/dates.js
> +
Two things:

* I've tried to keep most of the files in `filters/foo` generic and not register specific - so other teams could use them. As these are Register specific I'd put in `utils` or `app-misc`.
* There's already some filters for deriving an academic year from a date  - we should use that. We can pair on it.

2022-01-13 11:27 UTC, edwardhorsford commented on app/routes/records-list-routes.js
> +    if (!hasQueryString) filters.activeFutureHistoric = ["Current"]
Can you add a comment about the intent of this?

2022-01-13 11:27 UTC, edwardhorsford commented on app/views/_includes/trainee-record-card.njk
> +          <span class="app-nowrap">{{ record | getStartYear }}</span>
We already have an academic year on the record that we can use

2022-01-13 11:27 UTC, edwardhorsford commented on app/views/home.html
> +{# {% set records = data.filteredRecords | filterByYear(data.years.currentAcademicYear) %} #}
Is this needed?

2022-01-13 11:27 UTC, edwardhorsford commented on app/views/drafts.html
> +    <h1 class="govuk-heading-xl">Draft trainees {% include "_includes/trainee-count.njk" %}</h1>
I'd be tempted to include the entire h1 in the partial rather than doing an inline include.

2022-01-13 11:27 UTC, edwardhorsford commented on app/views/home.html
> +        {# <a class="govuk-link" href="/records?filterCycle=_unchecked">View all registered trainees ({{ registeredTrainees | length }})</a> #}
Is this needed?

2022-01-13 11:27 UTC, edwardhorsford commented on app/views/records.html
> +    <h1 class="govuk-heading-xl">{{pageBaseName}} {% include "_includes/trainee-count.njk" %}</h1>
As above, would include the h1 in the partial.

2022-01-13 11:57 UTC, ralph-hawkins commented on app/data/years.js
>    "2020 to 2021"
Removed

2022-01-13 12:00 UTC, ralph-hawkins commented on app/views/home.html
> +{# {% set records = data.filteredRecords | filterByYear(data.years.currentAcademicYear) %} #}
removed

2022-01-13 12:13 UTC, ralph-hawkins commented on app/views/drafts.html
> +    <h1 class="govuk-heading-xl">Draft trainees {% include "_includes/trainee-count.njk" %}</h1>
Yeah, much cleaner

2022-01-13 12:51 UTC, ralph-hawkins commented on app/views/home.html
> +        {# <a class="govuk-link" href="/records?filterCycle=_unchecked">View all registered trainees ({{ registeredTrainees | length }})</a> #}
removed

2022-01-13 13:06 UTC, ralph-hawkins commented on app/filters/dates.js
> +
yep — switched to record.courseDetails.academicYear and removed filters

2022-01-13 13:06 UTC, ralph-hawkins commented on app/views/_includes/trainee-record-card.njk
> +          <span class="app-nowrap">{{ record | getStartYear }}</span>
calling that

2022-01-18 11:49 UTC, edwardhorsford commented on app/data/years.js
> +  "2017 to 2018"
Do you know if `defaultVisibleYears` is still being used? we might be able to remove from the app as I think this work supersedes it.

2022-01-18 11:49 UTC, edwardhorsford commented on app/lib/utils.js
> +exports.isActiveStatus = record => {
Add a comment?

2022-01-18 11:49 UTC, edwardhorsford commented on app/views/_includes/trainee-count.njk
> +
might be tempted to call this file `trainee-count-heading` or similar

2022-01-18 11:52 UTC, edwardhorsford approved these changes

2022-01-18 11:58 UTC, ralph-hawkins commented on app/data/years.js
> +  "2017 to 2018"
i removed it

2022-01-18 12:58 UTC, merged