HESA records
DFE-Digital/register-trainee-teachers-prototype-old pull request #453
Opened 2022-02-18 17:17 UTC by ralph-hawkins

Register is importing HESA records. These records will be view only until the last update from HESA is imported.

Changed proposed:
- adds a check to see if a record can be edited
- makes records that should be locked view only (similar to lead schools — hides incomplete badges and change links)
- adds an explanation about the record being view only

![localhost_3000_record_92f655b3-e0f1-4a8e-96be-c1fdd59410e8(screenshot)](https://user-images.githubusercontent.com/8417288/154730884-e6780cf5-3d3d-4db5-9c06-add0763773aa.png)

2022-02-21 13:00 UTC, edwardhorsford requested changes

2022-02-21 13:00 UTC, edwardhorsford commented on app/filters/strings.js
> +  lastLetterOfString = string.split('').slice(-1)
you should lowercase the string.

2022-02-21 13:00 UTC, edwardhorsford commented on app/lib/utils.js
> +  if (source == "HESA") {
i'd use your `sourceIsHesa` filter here so we only have one way of checking this.

2022-02-21 13:00 UTC, edwardhorsford commented on app/lib/utils.js
> +  const isFinishingThisYear = (endAcademicYear == years.endOfCurrentCycle)
Maybe not for this PR, but we should consider these as generic filters.

2022-02-21 13:00 UTC, edwardhorsford commented on app/views/_includes/summary-cards/placements/placement-overview.html
> +        text: "Manage placements" if canAmend
Is this change intentional? I'm not entirely sure about 'manage' when you don't have edit rights.

2022-02-21 13:00 UTC, edwardhorsford commented on app/views/_templates/_record.html
> +  {% endif %}
Thoughts on this going in to an include?

2022-02-21 13:00 UTC, edwardhorsford commented on app/views/_templates/_record.html
> +        You will be able to recommend the trainee for QTS at the end of the academic year.
HESA is never EYTS, right?

2022-02-21 14:24 UTC, ralph-hawkins commented on app/filters/strings.js
> +  lastLetterOfString = string.split('').slice(-1)
Good point, I've made it handle upper case and lower case instead of forcing the string to lowercase.

2022-02-21 14:52 UTC, ralph-hawkins commented on app/views/_includes/summary-cards/placements/placement-overview.html
> +        text: "Manage placements" if canAmend
This hide "View" if the user doesn't have edit rights. I don't think the secondary view adds anything here as the content is the same and its unnecessary complexity in the (prod) codebase.

2022-02-21 14:53 UTC, ralph-hawkins commented on app/views/_templates/_record.html
> +  {% endif %}
sensible

2022-02-21 14:59 UTC, ralph-hawkins commented on app/views/_templates/_record.html
> +        You will be able to recommend the trainee for QTS at the end of the academic year.
Yeah, pretty sure

2022-02-21 16:05 UTC, edwardhorsford commented on app/views/_includes/summary-cards/placements/placement-overview.html
> +        text: "Manage placements" if canAmend
ah - in which case we should put a condition on the actions section entirely - I think this will output an anchor with empty text?

2022-02-21 16:10 UTC, ralph-hawkins commented on app/views/_includes/summary-cards/placements/placement-overview.html
> +        text: "Manage placements" if canAmend
Ah, yeah — good shout

2022-02-21 16:32 UTC, ralph-hawkins commented on app/lib/utils.js
> +  const isFinishingThisYear = (endAcademicYear == years.endOfCurrentCycle)
Done

2022-02-24 10:06 UTC, edwardhorsford requested changes

2022-02-24 10:06 UTC, edwardhorsford commented on app/filters/strings.js
> +  const lastLetterOfString = string.split('').slice(-1).toString()
```suggestion
  const lastLetterOfString = string.split('').slice(-1).toString().toLowerCase()
```

Just convert this to lowercase and then later compare to lowercase `s`

2022-02-24 10:06 UTC, edwardhorsford commented on app/filters/strings.js
> +    return string + "’"
```suggestion
  if (lastLetterOfString == "s") {
    return string + "’"
```

2022-02-24 10:06 UTC, edwardhorsford commented on app/filters/strings.js
> +    return string + "’S"
```suggestion
```

Don't think we need this? would we ever want capitalised possession?

2022-02-24 10:06 UTC, edwardhorsford commented on app/filters/strings.js
> +    return string + "’s"
Unsure what this is testing.

2022-02-24 10:06 UTC, edwardhorsford commented on app/lib/utils.js
> +  }
You don't really need this since the default is for it to be false.

2022-02-24 11:19 UTC, ralph-hawkins commented on app/lib/utils.js
> +  }
Removed

2022-02-24 11:22 UTC, edwardhorsford approved these changes

2022-02-24 11:23 UTC, merged