Bulk actions with error flow
DFE-Digital/register-trainee-teachers-prototype-old pull request #474
Opened 2022-03-24 13:26 UTC by ralph-hawkins

# Context

HEIs currently use the ITT provider portal to recommend trainees for QTS/EYTS and record their academic outcome. To improve the user’s experience and retire the ITT provider portal we need a way for users to recommend large groups of trainees for QTS/EYTS. 

We've added a way for users to download a template of trainees that are missing data or ready to be recommended for QTS/EYTS. The user can add the details and bulk update their records.

The adding missing information flow and the recommend flows are the same, but with different content and ask for different information.

# Screenshots

## Start of bulk changes flow

![localhost_3000_bulk-upload(screenshot)](https://user-images.githubusercontent.com/8417288/159922282-f1905dc1-f4e9-46d1-814e-50cac7094069.png)

## Add missing information flow

![localhost_3000_bulk-upload_add-details(screenshot)](https://user-images.githubusercontent.com/8417288/159922153-74d64e9e-dbba-43c4-9d65-ce350309264b.png)
![localhost_3000_bulk-upload_add-details_review-errors(screenshot)](https://user-images.githubusercontent.com/8417288/159922171-845e627f-294b-4ae6-b069-03b9dbff59d8.png)
![localhost_3000_bulk-upload_add-details_fix-errors(screenshot)](https://user-images.githubusercontent.com/8417288/159922174-01b1dfd7-dbeb-4177-bda5-dcb16652df2f.png)
![localhost_3000_bulk-upload_add-details_review-pending-updates(screenshot)](https://user-images.githubusercontent.com/8417288/159922177-e82e5a4b-c16e-48be-950d-c0fa8fda4c00.png)
![localhost_3000_bulk-upload_add-details_confirmation(screenshot)](https://user-images.githubusercontent.com/8417288/159922186-7a95e9ee-1c75-48f6-8029-019747e7ec78.png)

## Recommend for QTS/EYTS flow

![localhost_3000_bulk-upload_recommend(screenshot)](https://user-images.githubusercontent.com/8417288/159924996-26093551-d217-4a61-bf5e-5e110d5280e6.png)
![localhost_3000_bulk-upload_recommend_review-errors(screenshot)](https://user-images.githubusercontent.com/8417288/159925011-63ec1612-5258-472e-9134-e3ff99c0952d.png)
![localhost_3000_bulk-upload_recommend_fix-errors(screenshot)](https://user-images.githubusercontent.com/8417288/159925019-419b1a2c-0a25-4731-9844-639176602196.png)
![localhost_3000_bulk-upload_recommend_review-pending-updates(screenshot)](https://user-images.githubusercontent.com/8417288/159925023-dbff0a40-6c12-4cad-88e9-b7af90f0fcec.png)
![localhost_3000_bulk-upload_recommend_confirmation(screenshot)](https://user-images.githubusercontent.com/8417288/159925033-3b543d14-0fd7-47af-a022-07767ff1411b.png)

# Notes

- this assumes we won't need type of undergrad degree or undergrad degree grade 
- works on the same assumption that providers will give postgrad qualification ahead of the trainee getting it as the manual flow
- assumes CSV upload for v1, but there are advantages to Excel if we can handle virus scanning and the file format

2022-03-25 11:50 UTC, edwardhorsford requested changes

2022-03-25 11:50 UTC, edwardhorsford commented on app/filters/arrays.js
> +// A, B, C or D
Wrong comment?

2022-03-25 11:50 UTC, edwardhorsford commented on app/filters/strings.js
> +filters.makeNumberTwoDigits = (input) => {
Don't think we need this - we can use [padStart](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart)

Alternately, I'd make this filter more general purpose - take a string and a second arg for number of digits to pad.

2022-03-25 11:50 UTC, edwardhorsford commented on app/lib/utils.js
> +// Check if record has start date
Comment should mention it checks if the course has started, or perhaps the filter should just be simpler and not check that?

2022-03-25 11:50 UTC, edwardhorsford commented on app/lib/utils.js
> +exports.needsStartDate = function(record, data=false) {
Does this function need the second arg? It doesn't look like it's getting used.

2022-03-25 11:50 UTC, edwardhorsford commented on app/lib/utils.js
> +  if (exports.needsStartDate(record, data)) {
```suggestion
  if (exports.needsStartDate(record)) {
```

2022-03-25 11:50 UTC, edwardhorsford commented on app/lib/utils.js
> +}
Remove reference to data

2022-03-25 11:50 UTC, edwardhorsford commented on app/routes/bulk-upload-routes.js
> +    if (data.bulk.addDetailsFixErrors == "Yes, fix errors now" || data.bulk.addDetailsFixErrors == "Yes, fix error now") {
Can we give these radios a consistent value so we're not testing a changing label?

2022-03-25 11:50 UTC, edwardhorsford commented on app/routes/bulk-upload-routes.js
> +    data.bulk.addDetailsFixErrors = null
can we delete this instead?

2022-03-25 11:50 UTC, edwardhorsford commented on app/routes/bulk-upload-routes.js
> +    if (data.bulk.recommendFixErrors == "Yes, fix errors now" || data.bulk.recommendFixErrors == "Yes, fix error now") {
As above, let's test the value, not the label.

2022-03-25 11:50 UTC, edwardhorsford commented on app/routes/bulk-upload-routes.js
> +    data.bulk.recommendFixErrors = null
Delete rather than set to `null`

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/_includes/bulk-upload/errors-found.html
> +  <div class="govuk-grid-column-two-thirds">
```suggestion
  <div class="govuk-grid-column-two-thirds-from-desktop">
```

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/_includes/bulk-upload/errors-found.html
> +      <span class="govuk-caption-xl">{{ data.signedInProviders | andSeparate }}</span>
```suggestion
      <span class="govuk-caption-l">{{ data.signedInProviders | andSeparate }}</span>
```

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/_includes/bulk-upload/errors-found.html
> +            text: "Yes, fix " + errorPluralisation + " now"
Add value here in addition to `text`

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/_includes/bulk-upload/fix-errors.html
> +  <div class="govuk-grid-column-two-thirds">
```suggestion
  <div class="govuk-grid-column-two-thirds-from-desktop">
```

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/_includes/bulk-upload/fix-errors.html
> +      <span class="govuk-caption-xl">{{ data.signedInProviders | andSeparate }}</span>
```suggestion
      <span class="govuk-caption-l">{{ data.signedInProviders | andSeparate }}</span>
```

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/_includes/bulk-upload/fix-errors.html
> +      <a href="../public/assets/downloads/{{ bulkPath }}-fix-errors" download="{{ fileName}}">Download your trainee records with a description of the errors (csv)</a> or change your original file.
```suggestion
      <a class="govuk-link" href="../public/assets/downloads/{{ bulkPath }}-fix-errors" download="{{ fileName}}">Download your trainee records with a description of the errors (csv)</a> or change your original file.
```

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/_includes/bulk-upload/fix-pending-updates.html
> +      <span class="govuk-caption-xl">{{ data.signedInProviders | andSeparate }}</span>
```suggestion
      <span class="govuk-caption-l">{{ data.signedInProviders | andSeparate }}</span>
```

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/_includes/bulk-upload/fix-pending-updates.html
> +      <a href="../public/downloads/{{ bulkPath }}-change-pending.csv" download="{{ fileName }}">
```suggestion
      <a class="govuk-link" href="../public/downloads/{{ bulkPath }}-change-pending.csv" download="{{ fileName }}">
```

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/_includes/bulk-upload/review-pending-updates.html
> +      <span class="govuk-caption-xl">{{ data.signedInProviders | andSeparate }}</span>
```suggestion
      <span class="govuk-caption-l">{{ data.signedInProviders | andSeparate }}</span>
```

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/_includes/bulk-upload/review-pending-updates.html
> +    {% if data.bulk.recommendFixErrors == "Yes, fix errors now" or data.bulk.recommendFixErrors == "Yes, fix error now" %}
Change to single thing when you set a value rather than text

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/_includes/bulk-upload/review-pending-updates.html
> +      <a href="fix-pending-updates">Make changes to your pending updates</a>
```suggestion
      <a class="govuk-body" href="fix-pending-updates">Make changes to your pending updates</a>
```

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/admin.html
> +            text: "Bulk actions not bulk updates"
Think this could have a clearer name

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/admin.html
> +            text: "Bulk actions not bulk updates"
`Rename 'bulk actions' to 'bulk updates'`?

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/bulk-upload/add-details/confirmation.html
> +    <div class="govuk-grid-column-two-thirds">
```suggestion
    <div class="govuk-grid-column-two-thirds-from-desktop">
```

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/bulk-upload/add-details/confirmation.html
> +{% set traineesThatCanBeRecommended = currentTrainees | filterByComplete | filterByStatus(["Deferred", "Withdrawn", "QTS recommended", "QTS awarded", "EYTS recommended", "EYTS awarded"], true) %}
I wonder if we should make each of these a filter - that combines all the other filters.

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/bulk-upload/add-details/confirmation.html
> +{% set qualText = qualText | push("EYTS") if (traineesThatCanBeRecommended | filterOutEarlyYears) != traineesThatCanBeRecommended %}
I find this really hard to read - what's it doing?

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/bulk-upload/add-details/fix-errors.html
> +    {% set traineeInfo = trainee.personalDetails.shortName + '<br> <span style="color:  #505a5f">' + trainee.reference + '</span>' %}
Why a magic number?

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/bulk-upload/add-details/index.html
> +    <div class="govuk-grid-column-two-thirds">
```suggestion
    <div class="govuk-grid-column-two-thirds-from-desktop">
```

2022-03-25 11:50 UTC, edwardhorsford commented on app/views/bulk-upload/add-details/index.html
> +        <span class="govuk-caption-xl">{{ data.signedInProviders | andSeparate }}</span>
```suggestion
        <span class="govuk-caption-l">{{ data.signedInProviders | andSeparate }}</span>
```

2022-03-25 13:13 UTC, ralph-hawkins commented on app/filters/arrays.js
> +// A, B, C or D
No, but worried why you think it is?

2022-03-25 13:30 UTC, ralph-hawkins commented on app/filters/strings.js
> +filters.makeNumberTwoDigits = (input) => {
Make a more generic filter

2022-03-25 14:04 UTC, edwardhorsford commented on app/filters/arrays.js
> +// A, B, C or D
Ah it's because the other `thignSeparate` generally only separate with the word - eg space, and, with put those words between all items (except with, which uses `and` for the last item).

Here I expected the output of this to be `A or B or C`

2022-03-25 14:07 UTC, ralph-hawkins commented on app/lib/utils.js
> +// Check if record has start date
I've updated the comment. 

I think we need to be consistent with the rules around only asking for a start date, if the course has started.

2022-03-25 14:08 UTC, ralph-hawkins commented on app/lib/utils.js
> +exports.needsStartDate = function(record, data=false) {
Removed

2022-03-25 14:10 UTC, ralph-hawkins commented on app/lib/utils.js
> +  if (exports.needsStartDate(record, data)) {
👍🏻

2022-03-25 14:11 UTC, ralph-hawkins commented on app/lib/utils.js
> +}
👍🏻

2022-03-25 15:29 UTC, ralph-hawkins commented on app/routes/bulk-upload-routes.js
> +    if (data.bulk.addDetailsFixErrors == "Yes, fix errors now" || data.bulk.addDetailsFixErrors == "Yes, fix error now") {
yeah, much tidier

2022-03-25 15:29 UTC, ralph-hawkins commented on app/routes/bulk-upload-routes.js
> +    data.bulk.addDetailsFixErrors = null
yep 👍🏻

2022-03-25 15:37 UTC, ralph-hawkins commented on app/views/admin.html
> +            text: "Bulk actions not bulk updates"
Add more detail, including hint text

2022-03-28 15:58 UTC, ralph-hawkins commented on app/views/bulk-upload/add-details/confirmation.html
> +{% set qualText = qualText | push("EYTS") if (traineesThatCanBeRecommended | filterOutEarlyYears) != traineesThatCanBeRecommended %}
Fixed

2022-03-28 15:58 UTC, ralph-hawkins commented on app/views/bulk-upload/add-details/confirmation.html
> +{% set traineesThatCanBeRecommended = currentTrainees | filterByComplete | filterByStatus(["Deferred", "Withdrawn", "QTS recommended", "QTS awarded", "EYTS recommended", "EYTS awarded"], true) %}
Yep — changed to filters

2022-03-28 16:02 UTC, ralph-hawkins commented on app/views/bulk-upload/add-details/fix-errors.html
> +    {% set traineeInfo = trainee.personalDetails.shortName + '<br> <span style="color:  #505a5f">' + trainee.reference + '</span>' %}
Fixed

2022-03-30 10:09 UTC, edwardhorsford commented
I wonder if the instructions should use bold for the data items to call out - similar to how GovWifi does it
![Screenshot 2022-03-30 at 11 09 11](https://user-images.githubusercontent.com/2204224/160807562-828ef192-49f4-4b26-aac2-43c173abd36e.png)

2022-03-30 10:57 UTC, edwardhorsford requested changes
Looking good!

Some comments below:

Something we should test in UR: I wonder if we need to offer a range of identifiers to use - eg Provider ID, HESA ID, TRN. We could either provide all of these in the file, or ask a radio question to see what the provider prefers.

Should we have flash banners after upload? (I'm unsure on this)

The content sometimes refers to updates, and sometimes changes. Sometimes pending and sometimes not.

We probably don't want a back link on the confirm pages - there's nothing to go back to.

It's `PGCE` not `PCGE`

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/bulk-update/add-details/index.html
> +          You can find the URNs using <a href="https://www.get-information-schools.service.gov.uk/Search" class="govuk-link">Get information about schools</a>.
Should this force a new window?

2022-03-30 10:57 UTC, edwardhorsford commented on app/assets/downloads/add-details.csv
> +XD2746,,139032,
Should all these dates by dash separated?

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/bulk-update/add-details/index.html
> +        You can leave rows or cells empty if you do not want to updates those trainee records.
```suggestion
        You can leave rows or cells empty if you do not want to update those trainee records.
```

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/bulk-update/add-details/index.html
> +          You cannot add information in bulk if the school or setting does not have a URN, add those placements to the trainee record manually.
This sentence reads awkwardly with the comma. I think it either needs a semi-colon, or a dash, or a new sentence.

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/bulk-update/add-details/index.html
> +          id: "file-upload-1",
Should this explicitly restrict to csv extensions / file type?

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/_includes/bulk-update/errors-found.html
> +            text: "Yes, fix " + errorPluralisation + " now"
```suggestion
            text: "Yes, review and fix " + errorPluralisation + " now"
```

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/_includes/bulk-update/fix-pending-updates.html
> +      1. Export the pending updates file
I wonder if this should allow for `or continue with your existing file` or similar.

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/_includes/bulk-update/fix-pending-updates.html
> +      <a href="../public/downloads/{{ bulkPath }}-change-pending.csv"
This doesn't exist - should it?

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/_includes/bulk-update/check-pending-updates.html
> +          <a href="/bulk-update/cancel-bulk-changes" class="govuk-link">Cancel bulk changes to records</a>
Here you refer to `changes` where the rest of the content refers to updates

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/bulk-update/add-details/confirmation.html
> +        <a href="/bulk-update/" class="govuk-link">Bulk recommend trainees for {{ traineesThatCanBeRecommended | getQualifications | orSeparate }}</a>
```suggestion
        <a href="/bulk-update" class="govuk-link">Bulk recommend trainees for {{ traineesThatCanBeRecommended | getQualifications | orSeparate }}</a>
```

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/bulk-update/add-details/confirmation.html
> +        <a href="/bulk-update/" class="govuk-link">Bulk recommend trainees for {{ traineesThatCanBeRecommended | getQualifications | orSeparate }}</a>
Should this be linking to the recommend part of the flow? `bulk-update/recommend`

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/bulk-update/recommend/index.html
> +          Export trainee records with missing details (csv)
This filename is wrong.

2022-03-30 10:57 UTC, edwardhorsford commented on app/assets/downloads/recommend.csv
> +Do not change this column,"When the trainee started their ITT.
This is not the date they started their ITT

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/bulk-update/add-details/fix-errors.html
> +{% set pageHeading = "Fix the errors in your trainee records" %}
```suggestion
{% set pageHeading = "Fix errors in your trainee records" %}
```

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/bulk-update/recommend/fix-errors.html
> +{% set pageHeading = "Fix the errors in your trainee records" %}
```suggestion
{% set pageHeading = "Fix errors in your trainee records" %}
```

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/_includes/bulk-update/fix-errors.html
> +      Changes you make to this file will overwrite previous changes. For example, if you remove a row, changes made to that trainee will be lost.
Rather than saying changes will be lost, I think we could say that that trainee won't be updated.

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/_includes/bulk-update/fix-pending-updates.html
> +      Changes you make to this file will overwrite the previous pending changes. For example if you remove a row, changes made to that trainee will be lost.
I think we could say that the trainee won't be updated, not that anything will be lost.

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/bulk-update/recommend/check-pending-updates.html
> +    {% if trainee.route == "Assessment Only" %}
This checks uppercase `Only` but in the data it's `only` - so AO trainees are still being given postgraduate qualifications.

I think it might be easier if the seed data didn't include AO trainees though.

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/bulk-update/recommend/check-pending-updates.html
> +{% set pageHeading = "Check pending updates to trainee records" %}
I think this heading could be more explicit about this being the action to recommend for teaching status.

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/bulk-update/recommend/check-pending-updates.html
> +      text: "Teacher standard",
Teacher standard? Teaching standard?

`Teaching standard to be awarded`?

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/bulk-update/recommend/check-pending-updates.html
> +{% set tableBodyRows = [] %}
I wonder if we should do a separate table per teaching standard - one for QTS, and one for EYTS?

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/bulk-update/recommend/check-pending-updates.html
> +{% set tableHeadRow = [
I feel like the order of columns should be:

TRN,
Route and course,
Postraduate qualification
Date standards met
Teaching standard to be awarded

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/bulk-update/recommend/check-pending-updates.html
> +    },
Do we need study mode? else could it be folded in to route and course?

2022-03-30 10:57 UTC, edwardhorsford commented on app/views/_includes/bulk-update/check-pending-updates.html
> +          text: "Confirm updates to records"
Think this button text should explicitly mention 'recommend for x' where it's the recommend flow.

2022-03-30 12:24 UTC, ralph-hawkins commented on app/assets/downloads/add-details.csv
> +XD2746,,139032,
Nope — should be slashes.

2022-03-30 12:28 UTC, ralph-hawkins commented on app/views/bulk-update/add-details/index.html
> +          You can find the URNs using <a href="https://www.get-information-schools.service.gov.uk/Search" class="govuk-link">Get information about schools</a>.
I think it’s ok not to, the user is at the beginning of the flow and hasn't done any work. But I have the same thought every time I looked at the link. Do we generally force new windows elsewhere?

2022-03-30 13:18 UTC, ralph-hawkins commented on app/views/_includes/bulk-update/errors-found.html
> +            text: "Yes, fix " + errorPluralisation + " now"
👍🏻

2022-03-30 13:44 UTC, ralph-hawkins commented on app/views/bulk-update/add-details/confirmation.html
> +        <a href="/bulk-update/" class="govuk-link">Bulk recommend trainees for {{ traineesThatCanBeRecommended | getQualifications | orSeparate }}</a>
I was a little undecided. I felt that going back to the parent page might reassure the user as to what they were doing, help the go through the flow again in the future.

2022-03-30 13:45 UTC, ralph-hawkins commented on app/views/bulk-update/recommend/index.html
> +          Export trainee records with missing details (csv)
Are you sure, it works for me?

2022-03-30 14:07 UTC, ralph-hawkins commented on app/views/bulk-update/recommend/check-pending-updates.html
> +{% set tableBodyRows = [] %}
yeah, nice

2022-03-30 17:56 UTC, edwardhorsford commented on app/views/bulk-update/recommend/index.html
> +          Export trainee records with missing details (csv)
nothing downloaded for me.

2022-03-31 11:52 UTC, ralph-hawkins commented on app/views/_includes/bulk-update/check-pending-updates.html
> +          <a href="/bulk-update/cancel-bulk-changes" class="govuk-link">Cancel bulk changes to records</a>
yeah, made it consistent — thanks

2022-04-06 12:32 UTC, edwardhorsford commented on app/views/bulk-update/recommend/index.html
> +        2. Add details of the trainees outcome
Think this should either be:
* Add details of the trainee’s outcome
* Add details of trainee outcomes

2022-04-06 12:34 UTC, edwardhorsford commented on app/views/bulk-update/recommend/index.html
> +        was awarded teacher status.
I think technically it's the date they met the standards, not the date they're awarded. DfE does the awarding when they get recommended by the provider.

2022-04-06 12:38 UTC, edwardhorsford commented on app/filters/strings.js
> +filters.numberOfDigits = (input, targetLength) => {
don't think this filter name is clear. `padDigits` perhaps?

2022-04-06 12:38 UTC, edwardhorsford approved these changes

2022-04-06 15:38 UTC, merged