Bulk update move data to routes
DFE-Digital/register-trainee-teachers-prototype-old pull request #493
Opened 2022-04-14 15:37 UTC by ralph-hawkins

2022-04-20 09:38 UTC, edwardhorsford requested changes
Minor comments in code, which could be addressed later.

The csv you get when you first go down the recommend flow is broken - it's including stuff about errors and all squashed in to one cell.

This file seems oddly named?
<img width="855" alt="Screenshot 2022-04-20 at 10 36 42" src="https://user-images.githubusercontent.com/2204224/164199052-e3ea4a03-7f69-48bd-852e-eb2b04ac658a.png">

2022-04-20 09:38 UTC, edwardhorsford commented on app/lib/utils.js
> -exports.filterByCanBeRecommended = (records) => {
I wonder if this filter could simply:
* Check it's `TRN received`
* Check it's complete

I think it could also be general named more general purpose?

2022-04-20 09:38 UTC, edwardhorsford commented on app/routes/bulk-update-routes.js
> +    let processedRows = uploadedTrainees.map((trainee, index) => {
Could you add a brief comment for this function? Something like `For each record, randomly pick whether it's ok, in error, or unchanged. If in error, pick a random error`

2022-04-20 09:38 UTC, edwardhorsford commented on app/routes/bulk-update-routes.js
> +    const checkIfAnyUpdated = element => element.uploadStatus == "updated"
I don't think these are named correctly. They don't check for 'any' errors - they check if a single thing has an error. If you want to check any, this function should include the `.some()`

2022-04-20 10:47 UTC, ralph-hawkins commented on app/lib/utils.js
> -exports.filterByCanBeRecommended = (records) => {
True

2022-04-21 11:53 UTC, edwardhorsford approved these changes

2022-04-21 11:53 UTC, merged