Incident on wrong user getting access to Register - update request-an-account.html
DFE-Digital/register-trainee-teachers-prototype-old pull request #521
Opened 2022-05-18 15:42 UTC by MaeveRoseveare

1. Added in section about 'Who can get an account'

For the first bullet - would a school who does placements ever think that because they offer placements they are an ITT provider?

2. edited bullet to say 'training provider you work for' instead of 'you represent'

2022-05-18 15:54 UTC, edwardhorsford requested changes

2022-05-18 15:54 UTC, edwardhorsford commented on app/views/request-an-account.html
> +  </ul>
Indentation needs fixing on these

2022-05-18 15:54 UTC, edwardhorsford commented on app/views/request-an-account.html
> +  </ul>
Would it be worth linking to anything for each of these?

2022-05-18 15:54 UTC, edwardhorsford commented on app/views/request-an-account.html
> +    <p class="govuk-body">You can only get a Register account if you are:</p>
could this imply you need to be both?

2022-05-18 15:54 UTC, edwardhorsford commented on app/views/request-an-account.html
> +      <li>the name of the training provider or lead school you work for</li>
Should this refer to accredited provider?

2022-05-18 16:07 UTC, MaeveRoseveare commented on app/views/request-an-account.html
> +  </ul>
For accredited provider we could link to https://www.gov.uk/guidance/initial-teacher-training-itt-accreditation or https://www.gov.uk/government/collections/initial-teacher-training
I feel like the first link might be better as it explains there's a process to be an accredited provider, it's not just anyone

For lead school possibly: https://www.gov.uk/guidance/school-direct-guidance-for-lead-schools

2022-05-19 17:26 UTC, edwardhorsford approved these changes

2022-05-20 08:03 UTC, merged