Content for 3 news items
DFE-Digital/register-trainee-teachers-prototype-old pull request #652
Opened 2023-05-26 10:16 UTC by johndoates

2023-05-26 10:17 UTC, johndoates commented
![](https://github.trello.services/images/mini-trello-icon.png) [News items for bulk recommending, closure of TRA portal and removing home addresses](https://trello.com/c/UsrHUS8T/5524-news-items-for-bulk-recommending-closure-of-tra-portal-and-removing-home-addresses)

2023-05-26 13:03 UTC, edwardhorsford requested changes

2023-05-26 13:03 UTC, edwardhorsford commented on app/data/service-updates.yaml
> +      Read about [how to bulk recommend trainees](https://www.register-trainee-teachers.service.gov.uk/guidance/bulk-recommend-trainees).
```suggestion
      Read about [how to bulk recommend trainees](/guidance/bulk-recommend-trainees).
```

2023-05-26 13:03 UTC, edwardhorsford commented on app/data/service-updates.yaml
> +      Read about [how to withdraw, defer, reinstate or recommend a trainee for QTS or EYTS](https://www.register-trainee-teachers.service.gov.uk/guidance/withdraw-defer-reinstate-or-recommend-a-train
```suggestion
      Read about [how to withdraw, defer, reinstate or recommend a trainee for QTS or EYTS](/guidance/withdraw-defer-reinstate-or-recommend-a-trainee).
```

2023-05-26 13:03 UTC, edwardhorsford commented on app/data/service-updates.yaml
> +      Higher education institutions must now use this service to record outcomes for trainees registered using the Higher Education Statistics Agency (HESA) service.
```suggestion
      Higher education institutions (HEIs) must now use this service to record outcomes for trainees registered using the Higher Education Statistics Agency (HESA) service.
```

2023-05-26 13:03 UTC, edwardhorsford commented on app/data/service-updates.yaml
> +      Higher education institutions must now use this service to record outcomes for trainees registered using the Higher Education Statistics Agency (HESA) service.
I wonder if this should clarify what outcomes means - should we explicitly state award and withdraw? Should we state that this replaces the work they did in the TRA provider portal?

2023-05-26 13:03 UTC, edwardhorsford commented on app/data/service-updates.yaml
> +      Higher education institutions can now enable editing for trainees who were imported from HESA.
```suggestion
      Higher education institutions (HEIs) can now enable editing for trainees who were imported from HESA.
```

2023-05-26 13:21 UTC, johndoates commented on app/data/service-updates.yaml
> +      Higher education institutions must now use this service to record outcomes for trainees registered using the Higher Education Statistics Agency (HESA) service.
We don't strictly need to give the acronym since we don't refer to it later in the content. I'm happy to add it in case users are more likely to recognise it.

2023-05-31 17:34 UTC, johndoates commented on app/data/service-updates.yaml
> +      Higher education institutions must now use this service to record outcomes for trainees registered using the Higher Education Statistics Agency (HESA) service.
I was relying on the wording of the link to explain what we mean by outcomes but you're right that it would be clearer just to avoid the term. I've set out the details in bullets, as we did in emails about the changes sent to providers.

Since the heading says that Register has replaced the provider portal, I didn't think we needed to say it again in the body content. However, now that I've set out the outcomes in bullets I've found it useful to do that instead of saying that we're talking about trainees registered using HESA.

2023-06-02 09:48 UTC, edwardhorsford approved these changes

2023-06-02 10:21 UTC, merged