Withdraw flow
DFE-Digital/register-trainee-teachers-prototype-old pull request #71
Opened 2020-10-07 14:55 UTC by jesseyuen

This PR includes the withdrawal flow which I imagine we'll keep tweaking this as we know more.

Looking forward to your feedback!

2020-10-07 15:44 UTC, edwardhorsford requested changes

2020-10-07 15:44 UTC, edwardhorsford commented on app/routes.js
> +
Can these be deleted?

2020-10-07 15:44 UTC, edwardhorsford commented on app/views/_includes/forms/withdraw.html
> +      classes: "govuk-fieldset__legend--s govuk-!-margin-top-4 govuk-!-margin-bottom-4"
Question: are these margin overrides intentional?

2020-10-07 15:44 UTC, edwardhorsford commented on app/views/_includes/summary-cards/student-record.html
> +        classes: "govuk-tag--yellow govuk-!-margin-bottom-2"
```suggestion
        classes: record.status | getStatusClass + " govuk-!-margin-bottom-2"
```

2020-10-07 15:44 UTC, edwardhorsford commented on app/views/_includes/summary-cards/student-record.html
> +        classes: "govuk-tag--red govuk-!-margin-bottom-2"
```suggestion
        classes: record.status | getStatusClass + " govuk-!-margin-bottom-2"
```

2020-10-07 15:44 UTC, edwardhorsford commented on scripts/generate-records.js
> +  }
I think you could just make this equal to the updated date.

2020-10-08 09:18 UTC, jesseyuen commented on app/views/_includes/forms/withdraw.html
> +      classes: "govuk-fieldset__legend--s govuk-!-margin-top-4 govuk-!-margin-bottom-4"
They were... for now. Looking at these, it's a flow on from a duplicated markup (H1) isue. Sorting it.

2020-10-08 10:51 UTC, edwardhorsford approved these changes

2020-10-08 11:08 UTC, merged